### ISSUE TITLE
BouncyCastleJsseProvider errors in FIPS mode

### ISSUE THREAD

**Issue by sumeetaci** [bcgit/bc-java#926] opened 2021-04-07 00:21 UTC
Hi,
 We recently updated following jars:
bc-fips-debug-1.0.2.jar  from bc-fips-1.0.1.jar
bcpkix-fips-1.0.5.jar from bcpkix-fips-1.0.1.jar
bctls-fips-1.0.11.jar from bctls-fips-1.0.5.jar
We use java: java-1.8.0-openjdk-1.8.0.252.b09-2.el7_8.x86_64
OS: CentOS Linux release 7.8.2003
After updating jars, it is giving following errors only in FIPS mode on download from existing server:
No peer identity established
On another case while uploading a file to another server, it gives error:
upload script output: % failed Connection errorApr 06, 2021 1:56:02 PM org.bouncycastle.jsse.provider.PropertyUtils getBooleanSecurityProperty
INFO: Found boolean security property [keystore.type.compat]: true
Apr 06, 2021 1:56:03 PM org.bouncycastle.jsse.provider.PropertyUtils getStringSecurityProperty
INFO: Found string security property [jdk.tls.disabledAlgorithms]: SSLv3, RC4, MD5withRSA, DH keySize < 1024, EC keySize < 224, DES40_CBC, RC4_40, 3DES_EDE_CBC
Apr 06, 2021 1:56:03 PM org.bouncycastle.jsse.provider.PropertyUtils getStringSecurityProperty
...

Please suggest.

**Comment by sumeetaci** [comment] 2021-04-08 16:31
After debugging on, here are more details:
Apr  8 01:09:13 localhost javax.net.ssl.SSLPeerUnverifiedException: No peer identity established
Apr  8 01:09:13 localhost at org.bouncycastle.jsse.provider.ProvSSLSessionBase.getPeerCertificates(Unknown Source)
Apr  8 01:09:13 localhost at org.bouncycastle.jsse.provider.ExportSSLSession_7.getPeerCertificates(Unknown Source)
Apr  8 01:09:13 localhost at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:126)
Apr  8 01:09:13 localhost at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:437)

**Comment by peterdettman** [comment] 2021-04-12 08:35
This exception (SSLPeerUnverifiedException) happens when no certificate was received from the server. However it can be misleading because of the way Apache HttpClient 4.* uses JSSE; it has a quirk that it tries to access `SSLSession.getPeerCertificates` before it has confirmed whether the connection was even successful (see https://stackoverflow.com/a/12096206/264294 for some discussion).

Since BCJSSE doesn't support any cipher suites that would allow an anonymous server, then we can conclude that your handshake has actually failed, and you should be able to see the reason for that failure in your logs. Please change your Java Logging API logging level e.g. edit your JAVA_HOME/conf/logging properties:

```
#java.util.logging.ConsoleHandler.level = INFO
java.util.logging.ConsoleHandler.level = FINEST
org.bouncycastle.jsse.level = FINEST
```

It may also be helpful to use bctls-fips-debug-1.0.11.jar so that any stack trace will have more detail.

**Comment by sumeetaci** [comment] 2021-04-12 21:15
I have not done debugging in BC code yet. But, here is more info:
CertificateFactory.getInstance(algorithm, provider) is giving exception.
Failed to get CertificateFactory instance for the algorithm 'X.509' and the provider 'BCJSSE': CertificateException - X.509 not found

**Comment by peterdettman** [comment] 2021-04-13 14:23
You shouldn't be trying to find "X.509" CertficateFactory in "BCJSSE". It should be "BCFIPS". I think probably your provider configuration is wrong. Please show your provider configuration from java.security file or else the code that you are using to add the BCFIPS and BCJSSE providers.

**Comment by sumeetaci** [comment] 2021-04-13 17:32
Thanks for your reply. Actually, above log was after I changed provider from BCFIPS to BCJSSE to find if that is the cause. Our code has BCFIPS and not BCJSSE. I reverted it back. Here is the log after reverting and making it BCFIPS.
Apr 13 12:29:42 localhost WARN  com.bluecoat.clp.downloadutil.DownloadThread- Executing head request failed with SSLPeerUnverifiedException for service name : SubscriptionService, url : ..., DownloadResponse:   URI = https://...., StatusCode = 0, StatusMessage = null, ReasonMessage = null, AmountDownloaded = 0, DownloadDate = 2021-04-13T12:29:41.334+0000, CurrentlyDownloading = false, StartTime = null, EndTime = null, RequestToken = null, ETag = 
Apr 13 12:29:42 localhost javax.net.ssl.SSLPeerUnverifiedException: No peer identity established
Apr 13 12:29:42 localhost at org.bouncycastle.jsse.provider.ProvSSLSessionBase.getPeerCertificates(Unknown Source)
Apr 13 12:29:42 localhost at org.bouncycastle.jsse.provider.ExportSSLSession_7.getPeerCertificates(Unknown Source)
Apr 13 12:29:42 localhost at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:126)
Apr 13 12:29:42 localhost at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:437)
Apr 13 12:29:42 localhost at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
Apr 13 12:29:42 localhost at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
Apr 13 12:29:42 localhost at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:643)
Apr 13 12:29:42 localhost at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
Apr 13 12:29:42 localhost at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
Apr 13 12:29:42 localhost at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)

Here is java security file used for FIPS mode:
security.provider.1=org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider C:DEFRND[HmacSHA512];ENABLE{ALL};
security.provider.2=org.bouncycastle.jsse.provider.BouncyCastleJsseProvider fips:BCFIPS
security.provider.3=sun.security.provider.Sun

ssl.KeyManagerFactory.algorithm=SunX509
ssl.TrustManagerFactory.algorithm=PKIX

**Comment by peterdettman** [comment] 2021-04-14 05:19
You should set:
`ssl.KeyManagerFactory.algorithm=PKIX`

BCJSSE can only be used with its own PKIX `KeyManagerFactory` and `TrustManagerFactory`.

As I explained already, the exception you are seeing is misleading. The connection has failed earlier. Please collect logs as I described above so that we can see the original problem.

**Comment by sumeetaci** [comment] 2021-04-14 14:19
Thank you. In the code, we have configured to get KeyManagementAlgorithm as:
return isFipsModeEnabled() ? KEY_OR_TRUST_MANAGEMENT_ALGORITHM_PKIX : KEY_OR_TRUST_MANAGEMENT_ALGORITHM_SUNX509

Similar is done for TrustManagementAlgorithm.

**Comment by peterdettman** [comment] 2021-04-14 14:26
BCJSSE `SSLContext` can only be used with BCJSSE `KeyManagerFactory` "PKIX" and BCJSSE `TrustManagerFactory` "PKIX", regardless of FIPS mode. Anything else is not supported and will generally not work.

**Comment by dghgit** [comment] 2021-05-20 08:38
closing as appears resolved.

**Closed by dghgit** 2021-05-20 08:38 UTC

**Comment by ychernysh** [comment] 2023-09-28 15:36
> It may also be helpful to use bctls-fips-debug-1.0.11.jar so that any stack trace will have more detail.

@peterdettman I see this issue is almost 2 years old now, but where did you find `bctls-fips-debug` jar? I cannot find it in Maven central and this page is almost the only one my google search finds about it. I can find `bc-fips-debug` in Maven central though, but not `bctls-fips-debug`
Thanks!

**Comment by dghgit** [comment] 2023-09-28 18:12
We built one - it's also easy to build your own from the source jar for bctls - it's only dependencies are on other BC jars.
