### ISSUE TITLE
 org.bouncycastle.crypto.fips.FipsOperationError: Module checksum failed: expected [9f6751f059ab42f7d83e4e107881438036787e1e1821cd23a53c4b8181cc300f] got [db22a19266bc3d8485b00ed8fa24f2454b584bed02a365701c8900037d86099e]

### ISSUE THREAD

**Issue by prabusenthil** [bcgit/bc-java#1721] opened 2024-06-27 07:36 UTC
I am using the bc-fips 1.0.2.4 jar in my application. getting below exception

org.bouncycastle.crypto.fips.FipsOperationError: Module checksum failed: expected [9f6751f059ab42f7d83e4e107881438036787e1e1821cd23a53c4b8181cc300f] got [db22a19266bc3d8485b00ed8fa24f2454b584bed02a365701c8900037d86099e]

I want to add use this jar in my application .but it ends with the above error.

**Comment by peterdettman** [comment] 2024-06-27 07:54
Duplicate of https://github.com/bcgit/bc-java/issues/1415 .

**Closed by peterdettman** 2024-06-27 07:54 UTC
