### ISSUE TITLE
NoSuchAlgorithmException: Algorithm ECDH not available

### ISSUE THREAD

**Issue by anthony-o** [bcgit/bc-java#514] opened 2019-05-07 09:52 UTC
As I [explained on Stackoverflow](https://stackoverflow.com/q/55971726/535203), I'm trying to use BouncyCastle libraries to access to a Let's Encrypt secured website on JDK 1.6.

Here is the current stack I obtain:

    java.security.NoSuchAlgorithmException: Algorithm ECDH not available
	    javax.crypto.KeyAgreement.getInstance(DashoA13*..)
	    org.bouncycastle.jcajce.util.DefaultJcaJceHelper.createKeyAgreement(Unknown Source)
	    org.bouncycastle.tls.crypto.impl.jcajce.JcaTlsCrypto.calculateKeyAgreement(Unknown Source)
	    org.bouncycastle.tls.crypto.impl.jcajce.JceTlsECDomain.calculateECDHAgreement(Unknown Source)
	    org.bouncycastle.tls.crypto.impl.jcajce.JceTlsECDH.calculateSecret(Unknown Source)
	    org.bouncycastle.tls.TlsECDHEKeyExchange.generatePreMasterSecret(Unknown Source)
	    org.bouncycastle.tls.TlsProtocol.establishMasterSecret(Unknown Source)
	    org.bouncycastle.tls.TlsClientProtocol.handleHandshakeMessage(Unknown Source)
	    org.bouncycastle.tls.TlsProtocol.processHandshakeQueue(Unknown Source)
	    org.bouncycastle.tls.TlsProtocol.processRecord(Unknown Source)
	    org.bouncycastle.tls.RecordStream.readRecord(Unknown Source)
	    org.bouncycastle.tls.TlsProtocol.safeReadRecord(Unknown Source)
	    org.bouncycastle.tls.TlsProtocol.blockForHandshake(Unknown Source)
	    org.bouncycastle.tls.TlsClientProtocol.connect(Unknown Source)
	    org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(Unknown Source)
	    org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(Unknown Source)
	    sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:434)
	    sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:167)
	    sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1031)
	    sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:230)
	    org.jasig.cas.client.validation.Saml11TicketValidator.retrieveResponseFromServer(Saml11TicketValidator.java:216)

That is strange because it seems that such algorithm is registered by [`BouncyCastleProvider`](https://github.com/bcgit/bc-java/blob/4b133f18afe84364498f6f238a11e105e3e6df32/prov/src/main/java/org/bouncycastle/jce/provider/BouncyCastleProvider.java) (v1.61) which I'm using...

**Comment by catbref** [comment] 2019-05-09 12:38
I'm hitting this error too using 1.8u211 on win7 64bit trying to fetch from https://github.com using HttpsURLConnection:

```
2019-05-09 13:25:12 WARN  ProvTlsClient:-1 - Client raised fatal(2) internal_error(80) alert: Failed to read record
org.bouncycastle.tls.crypto.TlsCryptoException: cannot calculate secret
        at org.bouncycastle.tls.crypto.impl.jcajce.JceTlsECDomain.calculateECDHAgreement(Unknown Source)
        at org.bouncycastle.tls.crypto.impl.jcajce.JceTlsECDH.calculateSecret(Unknown Source)
        at org.bouncycastle.tls.TlsECDHEKeyExchange.generatePreMasterSecret(Unknown Source)
        at org.bouncycastle.tls.TlsProtocol.establishMasterSecret(Unknown Source)
        at org.bouncycastle.tls.TlsClientProtocol.handleHandshakeMessage(Unknown Source)
        at org.bouncycastle.tls.TlsProtocol.processHandshakeQueue(Unknown Source)
        at org.bouncycastle.tls.TlsProtocol.processRecord(Unknown Source)
        at org.bouncycastle.tls.RecordStream.readRecord(Unknown Source)
        at org.bouncycastle.tls.TlsProtocol.safeReadRecord(Unknown Source)
        at org.bouncycastle.tls.TlsProtocol.blockForHandshake(Unknown Source)
        at org.bouncycastle.tls.TlsClientProtocol.connect(Unknown Source)
        at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(Unknown Source)
        at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(Unknown Source)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source) [?:1.8.0_211]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) [?:1.8.0_211]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) [?:1.8.0_211]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) [?:1.8.0_211]
        at java.net.HttpURLConnection.getResponseCode(Unknown Source) [?:1.8.0_211]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source) [?:1.8.0_211]
Caused by: java.security.NoSuchAlgorithmException: Algorithm ECDH not available
        at javax.crypto.KeyAgreement.getInstance(KeyAgreement.java:184) ~[?:1.8.0_191]
        at org.bouncycastle.jcajce.util.DefaultJcaJceHelper.createKeyAgreement(Unknown Source)
        at org.bouncycastle.tls.crypto.impl.jcajce.JcaTlsCrypto.calculateKeyAgreement(Unknown Source)
        ... 22 more
```

With code along the lines of:

```
			URL url = new URL(uri);
			HttpURLConnection con = (HttpURLConnection) url.openConnection();

			try {
				con.setRequestMethod("GET");
				con.setConnectTimeout(5000);
				con.setReadTimeout(5000);
				setConnectionSSL(con);

				try {
					int status = con.getResponseCode();
```

Plus having to use the SNI work-around at described in issue #460 like this:

```
	public static void setConnectionSSL(HttpURLConnection con) {
		if (!(con instanceof HttpsURLConnection))
			return;

		HttpsURLConnection httpsCon = (HttpsURLConnection) con;
		URL url = con.getURL();

		httpsCon.setSSLSocketFactory(new org.bouncycastle.jsse.util.CustomSSLSocketFactory(httpsCon.getSSLSocketFactory()) {
			@Override
			protected Socket configureSocket(Socket s) {
				if (s instanceof SSLSocket) {
					SSLSocket ssl = (SSLSocket) s;

					SNIHostName sniHostName = new SNIHostName(url.getHost());
					if (null != sniHostName) {
						SSLParameters sslParameters = new SSLParameters();

						sslParameters.setServerNames(Collections.<SNIServerName>singletonList(sniHostName));
						ssl.setSSLParameters(sslParameters);
					}
				}

				return s;
			}
		});
	}
```

**Comment by catbref** [comment] 2019-05-09 15:46
I've found that a standalone class, e.g. foo.HttpsTest and not in a JAR, works, like this:
```
java -cp bcprov-jdk150on-162b15.jar:bctls-jdk150on-162b15.jar:classes foo.HttpsTest
```

Whereas before I was using/testing with a class packaged inside a shaded/uber/fat JAR.
However, if I prepend that BC JARs before the fat-JAR that also works:
```
java -cp  bcprov-jdk150on-162b15.jar:bctls-jdk150on-162b15.jar:fat.jar foo.HttpsTest
```

So maybe one of the other included dependencies in my fat JAR is somehow affecting BouncyCastle?

How does this compare with your situation, @anthony-o ?

**Comment by catbref** [comment] 2019-05-09 16:56
OK, so everything seems to work fine with Java 8u202 but not 8u211?!

**Comment by peterdettman** [comment] 2019-05-14 10:12
> That is strange because it seems that such algorithm is registered by [`BouncyCastleProvider`](https://github.com/bcgit/bc-java/blob/4b133f18afe84364498f6f238a11e105e3e6df32/prov/src/main/java/org/bouncycastle/jce/provider/BouncyCastleProvider.java) (v1.61) which I'm using...

Please show code for how you are using it. Your issue seems like a very simple one of failing to register the BC provider. Ignore all the TLS/JSSE stuff for the moment and get this working:

```
    Security.insertProviderAt(new BouncyCastleProvider(), 1);
    KeyAgreement ka = KeyAgreement.getInstance("ECDH");
    System.out.println(ka.getProvider().getName());
```

That is expected to just print "BC". This only requires that you have the bcprov (or bcprov-ext) jar in your classpath. "ECDH" definitely exists, so if you see NoSuchAlgorithmException it's because you haven't registered the provider properly.

If you see java.lang.SecurityException: JCE cannot authenticate the provider BC, then you may have modified the provider jar somehow (bcprov/bcprov-ext). It is signed and cannot be repackaged or rebuilt without invalidating that signature. Another common cause is a truncated download of the jar, so please verify the checksum (https://www.bouncycastle.org/checksums.html).

Once that is working, you can then *also* register the BCJSSE provider (you need *both* providers):

    Security.insertProviderAt(new BouncyCastleJsseProvider(), 1);
    Security.insertProviderAt(new BouncyCastleProvider(), 1);

That one now needs the bctls jar to *also* be present (again confirm the checksum).

BTW, in reference to the stackoverflow issue, when using BCJSSE you should configure:
```
    ssl.KeyManagerFactory.algorithm=PKIX
```

in java.security, rather than "X.509".

**Comment by peterdettman** [comment] 2019-05-14 10:27
@catbref I've tested here with jkd1.8.0_211 and don't see any problems. From some of your comments it sounds like you might have been repackaging jars, which is a no-no for bcprov. Also, were you installing jars into jre/lib/ext at any point?

I would suggest a clean install of 8u211 following the steps you used to get 8u202 working. In the unlikely event there is a real conflict, please open a new issue with a (small ) self-contained test program demonstrating the problem.

**Comment by catbref** [comment] 2019-05-21 11:50
I can confirm that in my case, repackaging was the cause of my error.
Repackaging essentially 'unsigned' the BC jars and Java SE (unlike OpenJDK) refused to consider BC as a security provider as a result.
Sorry for the added confusion.

**Comment by bcgit** [comment] 2019-07-20 01:33
Closed as due to provider repackaging.

**Closed by bcgit** 2019-07-20 01:33 UTC

**Comment by lapo-luchini** [comment] 2020-08-31 15:56
I managed to reproduce this bug with _no re-packaging_ in place using Oracle JRE 1.6.0_43 (yes, I know that's ancient, I'm trying to convince my client to upgrade) on BC 1.61, but it works correctly by downgrading to BC 1.60.

I didn't go in deeper, but I guess the JAR signature algorithm changed in BC 1.61 and that Java 6 doesn't know how to verify the new signature… or something like that.

**Comment by lapo-luchini** [comment] 2020-08-31 16:23
Can reproduce with:
```Java
public class TestECDH {
    public static void main(String[] args) throws Exception {
        java.security.Provider prov = new org.bouncycastle.jce.provider.BouncyCastleProvider();
        java.security.Security.addProvider(prov);
        javax.crypto.KeyAgreement ka = javax.crypto.KeyAgreement.getInstance("ECDH");
        System.out.println("Java version: " + System.getProperty("java.version"));
        System.out.println("BC version: " + prov.getVersion());
        System.out.println("ECDH: " + ka);
    }
}
```

With the following commands:
```cmd
C:\test6bc>"C:\Program Files (x86)\Java\jre6\bin\java.exe" -cp target\classes;%USERPROFILE%\.m2\repository\org\bouncycastle\bcprov-jdk15on\1.60\* TestECDH
Java version: 1.6.0_43
BC version: 1.6
ECDH: javax.crypto.KeyAgreement@147c5fc

C:\test6bc>"C:\Program Files (x86)\Java\jre6\bin\java.exe" -cp target\classes;%USERPROFILE%\.m2\repository\org\bouncycastle\bcprov-jdk15on\1.61\* TestECDH
Exception in thread "main" java.lang.SecurityException: JCE cannot authenticate the provider BC
        at javax.crypto.SunJCE_b.a(DashoA13*..)
        at javax.crypto.KeyAgreement.getInstance(DashoA13*..)
        at TestECDH.main(TestECDH.java:11)
Caused by: java.util.jar.JarException: Cannot parse file:/C:/Users/lapo/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.61/bcprov-jdk15on-1.61.jar
        at javax.crypto.SunJCE_c.a(DashoA13*..)
        at javax.crypto.SunJCE_b.b(DashoA13*..)
        at javax.crypto.SunJCE_b.a(DashoA13*..)
        ... 3 more
```
