### ISSUE TITLE
lcrypto-jdk12-177 org.bouncycastle.crypto.test.RegressionTest fails with 3 StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by t-arn** [bcgit/bc-java#1600] opened 2024-03-11 13:18 UTC
Hello folks,
I successfully compiled lcrypto-jdk12-177 with JDK6 and ran the test org.bouncycastle.crypto.test.RegressionTest

It fails with following failures:
Completed with 3 FAILURES:
=>  SHA-3: Exception: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
=>  HC-128 and HC-256 (ecrypt): Exception: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
=>  SCrypt: Exception: java.lang.StringIndexOutOfBoundsException: String index out of range: -1

Can anybody tell me what is wrong here?

Thank you
Tom
[crypto-RegressionTest.log](https://github.com/bcgit/bc-java/files/14559109/crypto-RegressionTest.log)

**Comment by t-arn** [comment] 2024-03-13 06:50
I need the Bouncycastle library for a Java compatible VM which is only JDK 1.2 compatible.
And I used JDK6 to compile because modern Java compiler do not support 1.2 class format anymore.

**Comment by dghgit** [comment] 2024-03-14 03:58
Okay, I think the errors are probably not important, in the sense they show something has gone terribly wrong, if that's the case. It would be worth spending some time checking the individual test cases just to see what's causing them though. If you look at the RegressionTest class you'll see it just invokes all the other tests one after the other - it's also possible to run the individual tests for debugging purposes.

**Comment by t-arn** [comment] 2024-03-14 18:12
I found the problem: The file lcrypto-jdk12-177.zip does not contain the .txt files expected by these 3 tests.
In fact, it does not contain any .txt files.

**Comment by dghgit** [comment] 2024-03-15 11:45
Ah... packaging issue... sorry about that. Thanks, I'll have a look at what's happening. Will let you know.

**Comment by dghgit** [comment] 2024-03-16 09:36
Actually, no it looks like you need a copy of bc-test-data cloned as well. If you check it out at the same level as the parent directory of where you run the test (the test data locator searches back up the directory tree looking for a directory called bc-test-data) you should find it locates the files.

**Comment by dghgit** [comment] 2024-04-22 09:17
Assumed fixed with bc-test-data.

**Closed by dghgit** 2024-04-22 09:17 UTC
