### ISSUE TITLE
Certificates without versions are not parsed.

### ISSUE THREAD

**Issue by idavkaev** [bcgit/bc-java#518] opened 2019-05-14 11:37 UTC
Hi, 

It looks like the certificate without versions are not parsed.

Example:

> -----BEGIN CERTIFICATE-----
> MIICkzCCAfygAwIBAwIERhnVjjANBgkqhkiG9w0BAQQFADCBjTELMAkGA1UEBhMC
> VVMxEjAQBgNVBAgTCUxvdWlzaWFuYTEMMAoGA1UEBxMDTlNLMRQwEgYDVQQKEwtT
> d3NvZnQsIEluYzEMMAoGA1UECxMDMTIzMRUwEwYDVQQDEwxzc2x0ZXN0LmJjb20x
> ITAfBgkqhkiG9w0BCQEWEm9sZ2FAbG9jYWxob3NkLm5ldDAeFw0wNzA0MDkwNTMz
> NDNaFw0xMjA0MDkwNTMzNDNaMIGNMQswCQYDVQQGEwJVUzESMBAGA1UECBMJTG91
> aXNpYW5hMQwwCgYDVQQHEwNOU0sxFDASBgNVBAoTC1N3c29mdCwgSW5jMQwwCgYD
> VQQLEwMxMjMxFTATBgNVBAMTDHNzbHRlc3QuYmNvbTEhMB8GCSqGSIb3DQEJARYS
> b2xnYUBsb2NhbGhvc2QubmV0MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDM
> GGsfsVsajf9z3EfYhOw8wOX6tUkZFT8U9ZKfIvBSl4n7kvtmBsUhx5/h854sJcok
> mnVyDQ+GGjPyggRlnFkp+ufiTenOSDmqtK5XzFRsovXH0iNecINkJ53cdJOT4dIX
> K7fGj0VyVmFwVJ7M21TKZBEbO9TwO7CVW6sP/G83gwIDAQABMA0GCSqGSIb3DQEB
> BAUAA4GBALsIYYU82hJglpZgbT2acxq/ZiaD21rJgBuvzzsQkAQLlNxegbbP8g+4
> YGdC9vyxEIExb0ixPfAd4ReE9m2C+tFt2eTndt24Bgo27ga0tzx6UKUvl3NLUXGA
> lpZpZqlNiczwz/R5Y40aRnGfgvdihnMsjLEuNFtazRRf+oLcWdiL
> -----END CERTIFICATE-----

That one has the following data:
```
Certificate:
    Data:
        Version: Unknown (3)
        Serial Number: 1176098190 (0x4619d58e)
    Signature Algorithm: md5WithRSAEncryption
        Issuer: C = US, ST = Louisiana, L = NSK, O = "Swsoft, Inc", OU = 123, CN = ssltest.bcom, emailAddress = olga@localhosd.net
        Validity
            Not Before: Apr  9 05:33:43 2007 GMT
            Not After : Apr  9 05:33:43 2012 GMT
        Subject: C = US, ST = Louisiana, L = NSK, O = "Swsoft, Inc", OU = 123, CN = ssltest.bcom, emailAddress = olga@localhosd.net
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (1024 bit)
                Modulus:
                    00:cc:18:6b:1f:b1:5b:1a:8d:ff:73:dc:47:d8:84:
                    ec:3c:c0:e5:fa:b5:49:19:15:3f:14:f5:92:9f:22:
                    f0:52:97:89:fb:92:fb:66:06:c5:21:c7:9f:e1:f3:
                    9e:2c:25:ca:24:9a:75:72:0d:0f:86:1a:33:f2:82:
                    04:65:9c:59:29:fa:e7:e2:4d:e9:ce:48:39:aa:b4:
                    ae:57:cc:54:6c:a2:f5:c7:d2:23:5e:70:83:64:27:
                    9d:dc:74:93:93:e1:d2:17:2b:b7:c6:8f:45:72:56:
                    61:70:54:9e:cc:db:54:ca:64:11:1b:3b:d4:f0:3b:
                    b0:95:5b:ab:0f:fc:6f:37:83
                Exponent: 65537 (0x10001)
    Signature Algorithm: md5WithRSAEncryption
         bb:08:61:85:3c:da:12:60:96:96:60:6d:3d:9a:73:1a:bf:66:
         26:83:db:5a:c9:80:1b:af:cf:3b:10:90:04:0b:94:dc:5e:81:
         b6:cf:f2:0f:b8:60:67:42:f6:fc:b1:10:81:31:6f:48:b1:3d:
         f0:1d:e1:17:84:f6:6d:82:fa:d1:6d:d9:e4:e7:76:dd:b8:06:
         0a:36:ee:06:b4:b7:3c:7a:50:a5:2f:97:73:4b:51:71:80:96:
         96:69:66:a9:4d:89:cc:f0:cf:f4:79:63:8d:1a:46:71:9f:82:
         f7:62:86:73:2c:8c:b1:2e:34:5b:5a:cd:14:5f:fa:82:dc:59:
         d8:8b
```

Attempt to parse ends with error:
problem parsing cert: org.bouncycastle.cert.CertIOException: malformed data: version number not recognised

Piece of stack:
```
org.bouncycastle.openssl.PEMParser$X509CertificateParser.parseObject(Unknown Source)
org.bouncycastle.openssl.PEMParser.readObject(Unknown Source)
```

Thank you

**Comment by peterdettman** [comment] 2019-05-14 14:05
This certificate does have a version; it encodes the *value* 3 in its TBSCertificate.version field, but the highest valid version *value* is 2, corresponding to a V3 certificate (yes, it's off-by-1).

**Comment by idavkaev** [comment] 2019-05-15 02:08
Hi Peter,

Thank you for replying.
But the certificate is valid. It was handled by bcprov-jdk15on-1.56.jar (and earlier versions) just fine until it was upgraded to 1.60.

**Comment by peterdettman** [comment] 2019-05-15 03:56
https://github.com/bcgit/bc-java/commit/8df14f6e07399ef827e7f954ad0e99d358dd070b introduced validation of the version in TBSCertificate. That was released shortly afterwards, in 1.58. The certificate was always invalid, but earlier BC releases ignored the error.

**Comment by bcgit** [comment] 2019-07-13 00:30
Closing as (unfortunately) not a bug.

**Closed by bcgit** 2019-07-13 00:30 UTC

**Comment by ralfhauser** [comment] 2020-02-16 17:56
also got
java.lang.IllegalArgumentException: version number not recognised
	at org.bouncycastle.asn1.x509.TBSCertificate.<init>(Unknown Source)
	at org.bouncycastle.asn1.x509.TBSCertificate.getInstance(Unknown Source)
	at org.bouncycastle.asn1.x509.Certificate.<init>(Unknown Source)
	at org.bouncycastle.asn1.x509.Certificate.getInstance(Unknown Source)
	at org.bouncycastle.cert.jcajce.JcaX509CertificateHolder.<init>(Unknown Source)
	at org.bouncycastle.openssl.jcajce.JcaMiscPEMGenerator.convertObject(Unknown Source)
	at org.bouncycastle.openssl.jcajce.JcaMiscPEMGenerator.<init>(Unknown Source)
	at org.bouncycastle.openssl.PEMWriter.writeObject(Unknown Source)
	at org.bouncycastle.openssl.PEMWriter.writeObject(Unknown Source)

for 
-----BEGIN CERTIFICATE-----
MIIDdzCCAl+gAwIBAwIJAPjc4aDV0NqAMA0GCSqGSIb3DQEBBQUAMHsxCzAJBgNV
BAYTAkJBMRwwGgYDVQQDDBNTTUZpemlja2lTZWxmc2lnbmVkMREwDwYDVQQHDAhT
YXJhamV2bzEQMA4GA1UECgwHRS12bGFkYTEcMBoGA1UECAwTQm9zbmEgaSBIZXJj
ZWdvdmluYTELMAkGA1UECwwCSVQwHhcNMTkxMjA2MTUyNTM3WhcNMjkxMjAzMTUy
NTM3WjB7MQswCQYDVQQGEwJCQTEcMBoGA1UEAwwTU01GaXppY2tpU2VsZnNpZ25l
ZDERMA8GA1UEBwwIU2FyYWpldm8xEDAOBgNVBAoMB0UtdmxhZGExHDAaBgNVBAgM
E0Jvc25hIGkgSGVyY2Vnb3ZpbmExCzAJBgNVBAsMAklUMIIBIjANBgkqhkiG9w0B
AQEFAAOCAQ8AMIIBCgKCAQEAnKuT3LmUPRLTiOF5fySpbf1kePknIt52BULkEYEr
n8+YV/E0ST8fMEpkaJtt6B1eMK1v0avIpBXVFaGRF+U9NCk+qC4GrbdczwKkcnvy
47B8zUJflxp0tP1h9NgCOczi9wLYjbG9CliLTd5R9Hohh/XVzgu1UqLzk/pCPbQK
CMaxCLYKANwueiNM/01TIADDzLYbWBCTdQdXAx+czUWOWP0S56HDydGM9RcfHeuT
RuQSE/HQ8wTnAHNfETiV2IeyaZ7LV6G/3l3BIzHkiWCNlF20W3ZmZRg2qdq4npVY
QfeVwVTyMr2JjtPhytu8Aq8u9U7SLkNuwsT8BuM+ZBKldQIDAQABMA0GCSqGSIb3
DQEBBQUAA4IBAQBfFbsYSAq1vI+QliEgFQTVsH+inCpOLAHSHuW4V0F2FIBtS/e2
NpQwq4h+aSfYdDMl7rC4gzbE/roPIXh0txI+i7n8CGcCcMosOSzoyZCaWS9t7sl+
yLYWn5WVpLl59acfqI5RjI/GaHViPZasJch51PaQBoM629mYuXwWO4mJzwxtM7KP
Gv/9mTBQEqpV/ThP7Z2CixnI9yVVMdg7aNqNhZZGB8ZqDaJhD0pOBHun6aCatkKI
4lRH3ZUEQBG5u/qeEAGkHjsB2tQDGf1/LG5n5gIvYF359FUX2wk+nxQgEbmtB48J
zJXE8ILSuz3A169O7Ecd6H3v2tpW9TzA/qEt
-----END CERTIFICATE-----

Interestingly, openssl or xca do not complain.

If it is the same, it would be great to
1) provide a more precise error message stating what the value found was and what the permitted values are
2) allow for a lenient/graceful treatment like above "Version: Unknown (3)"
(as done by openssl x509 -in cerfile.cer -noout -text)

**Comment by erdbeerschnitzel** [comment] 2023-03-05 18:28
Is this still the full truth in 2023? 
Please have a look at the discussion in https://github.com/openssl/openssl/issues/6599

"Implementations SHOULD be prepared to accept any version certificate" https://www.ietf.org/rfc/rfc5280.txt
