### ISSUE TITLE
CMSAuthEnvelopedData and CMSAuthEnvelopedGenerator java classes have only package access

### ISSUE THREAD

**Issue by wolftobias** [bcgit/bc-java#528] opened 2019-06-04 12:20 UTC
The two java files CMSAuthEnvelopedData and CMSAuthEnvelopedGenerator have only package access and it seems the implementation is not finished yet.
Background is I need to create a 1.2.840.113549.1.9.16.1.23 authEnvelopedData ASN1 structure and I tried to solve this with bouncycastle but the two classes are not really available for usage.

**Comment by peterdettman** [comment] 2019-06-06 04:18
Yes, these are placeholder classes for implementing RFC 5083 (and 5084). Unfortunately considerable work remains before they would be usable.

**Comment by MadMud** [comment] 2019-06-06 10:18
Hi,
I have written these for work. If there is interest I can ask if I am allowed to create a PR from this...
If not I can at least provide test vectors.

If memory serves you need to also add GCM in AES. The Algorithms are there but the CMS codec things are not there.

**Comment by wolftobias** [comment] 2019-06-06 12:36
If you could provide some input, I would be very appreciate.

**Comment by bcgit** [comment] 2019-06-10 01:02
@MadMud PR would be welcome providing you're happy with any code going out using the BC license. Test vectors are extremely important. Thanks.

**Comment by wolftobias** [comment] 2019-06-14 07:04
@MadMud Are there any new regarding your PR?

**Comment by MadMud** [comment] 2019-06-14 09:02
I have not heard back from my contacts at work. I think I will proceed with rewriting what is needed without my code from last year...

**Comment by bcgit** [comment] 2019-06-15 01:34
Ah, okay. This is starting to sound a bit grey. In this case, are you able to send some test vectors first? If we have those we can at least pull a parser together and probably a generator as well. At least then it would be clear that any subsequent contributions from you was on code that was external to your organization.

**Comment by wolftobias** [comment] 2019-06-17 07:07
@MadMud Now it`s your turn ;-), what is you plan? Are you going to support this?

**Comment by MadMud** [comment] 2019-06-19 22:05
Hi again, 
Had to care for a sick child for a week, but now I again have some free time :)

Anyway, I am unsure in which format to dump testvector on here. For starters lets got with [1], the key is [2] and the cleartext is "auth-enveloped data".

I propose to advance in one of two ways:
a) I can implement the basic functionality separate from the existing CMSEnvelopedDataStreamGenerator  et. al. This will involve quite a bit of code duplication, since most of the code from there needs to run also in the authenveloped case, We can discuss on how to remove this duplication in a second step.
b) I can write a integrated implementation that will share its code with the existing classes, this however means I will have to touch the whole envelopedData codec suite from the get go. And since you do not know me you might want something you can scrap, or rewrite using your coding style...

I do not mind either way, but would like to clarify an interface issue in both cases:

Right now the user will specify the symmetric encryption method via the ContentEncryptionBuilder. From that the CMSEnvelopedDataGenerator *could* infer if in fact auth-enveloped or enveloped data is needed. This would make it trivial for downstream developers to support auth-enveloped. The downside is of course that now the CMSEnvelopedDataGenerator is actually a CMSEnvelopedOrAuthenvelopedGenerator (*sigh*) and users looking to explicitly do auth-enveloped might miss it altogether. The same issue arises in decoding: we can just decode both enveloped and auth-enveloped in one method, or provide separate versions. Here I feel the precedence of signed and compressed data might suggest that we want to do it separately though. 
Cheers,
MadMud

[1]
MIAGCyqGSIb3DQEJEAEXoIAwgAIBADGBmzCBmAIBAoABATANBgkqhkiG9w0BAQEFAASBgG9yJPC3zFmIbPTtSrrTD+71lluua3F1/V/XzzDOczjdymy4tI4sle5HSxJN8yrw+m2JdWKb4s/u4frvmNqE6fcqfFtLpLEMXJneoEWWXZFKbndoqQNRMgfKGCncpeWhktRcSRtbEEk/H4hWggJGmVClS7f/nmCDjwyANBnI3shYMIAGCSqGSIb3DQEHATAfBglghkgBZQMEAQYwEgQQLO0PwnuhYXRk8pLLhgik0aCABB8KvxIkbmBKT73Oz4xtf0DNNGmdn+tzPcOldJUQWCEnAAAAAAQMn+tzPcOldJUQWCEnAAAAAAAA

[2]
MIICdAIBADANBgkqhkiG9w0BAQEFAASCAl4wggJaAgEAAoGBAMtFuFyzl4jgeuPL
uGp8Niqf11QGWVDTpZvE7VabLoPanzuVgjTYC8oJOq4PvVYW5V56KeGzXhsnhsDt
IBaRESTFuXM50uiH4mRPGsqCFJvbmokvxfhb24TPg3gQ5E2SEvmXFN425J/jvcqq
XpX7wQGtr9DWLIXsqPeLKhoy/qdhAgMBAAECf3xBB80spVPEggTXW2aoebwXt1pw
8BqzUnSWqlZaHJGdtgbxL0qNsjECX42Djj+1vzddJud0dRHvu4m8y8zlVl/Ro+fv
xETE9nCKzt1MlaNUG9mywZeWLjyOKZFY5fxc+yzoH+d8fcXTM7SwKG9bl6hisU0j
LWdramL5eV/kILECQQDxD5WuYZY2gF2DhtqAxCaf2MLgDlXzj1PcX3X1nPlrNKy3
G0jyMWofmZFORzUz1G0Dlyfxk3Wlc+1IIWbxH5dNAkEA196fcWJN9ZpavkuLKG3W
5sSWAs05Jdk2FGw/pbycoIaMOtf/3KeWJTSNxK1jKsoTQN3RUF9h2jtFhf+yqOjO
ZQJAGpf7jVdauPyEVIRGCrqZAD1rkkhClzISsFcfrk74/Si8fR7Xd1CYQpAwhZA5
gFRJCoJcd7wq2Gvnm3OD5cn0aQJAP98H8CV1CaltFgcGGqU9Q7SA6j1Mnm1BehN5
VZGUCk8lKLgGZYRUgZemJr5irCN0ROoc55oBOu/0pyw78YxInQJBAKjibmupsLLt
kUQF7vyalONmkebwEDwTHODWOGXC7xmcvXhFAnlpYkv3QCohF53X0RS+VprfojbI
X0T/eAP0zJA=

**Comment by wolftobias** [comment] 2019-07-01 13:43
@bcgit @MadMud Is there anybody working on this? What's the current status?

**Comment by wolftobias** [comment] 2019-07-01 13:44
@MadMud I understand [1] but for what is the [2] good for?

**Comment by bcgit** [comment] 2019-07-04 08:59
I've checked in enough to decrypt the current message. Are you able to produce a sample which includes authenticated attributes - that's really where the tricky bit is.

**Comment by wolftobias** [comment] 2019-07-22 07:25
I was trying around with diverse asn1 generator tools, but it's needed to do also some encryption and signing on these test vectors, therefore it's not so easy to generate them.

**Comment by MadMud** [comment] 2019-07-23 18:46
Hi Tobias,
This data is not actually signed but, a Mac is is attached after the authenticated attributes and that is compared to what the recieving party is getting. You will not have to implement any of this though. At least for aes/gcm this is already done. The encryptor passed to the xxxGenerator will have to be a MacProvider, else the algo cannot be used for auth enveloped (e.g. aes/cbc will not work - yeah one could define a separate authentication algorithm, but I do not think this is what was intended by the standard)

Anyway, for work I never implemented authAttributes, because I had no usecase... But I do not think this would be complicated, add the attributes before you calculate the Mac, and compare them after decode.

As I said in my last message, implementing this is quite straight forward, but there are interface issues I pointed out. I am not sure how code ownership in bc is handled, but I deal I should not redesign the CMS codec interfaces without feedback from some coredevs...

Cheers,
Matthias

**Comment by MadMud** [comment] 2019-07-23 19:33
Hi,
After re-reading rfc5083 and rfc3852 9.2 I now remember why I did not implement auth-attributes without a clear usecase back when I worked on this. This is indeed quite involved. However, we should be able to reuse DefaultAuthenticatedAttributeTableGenerator or something near this.
So I am sorry to report that I cannot provide test vectors for this case easily, but will investigate the above..
Cheers
Matthias

**Comment by MadMud** [comment] 2019-07-23 20:24
Sorry for all the SPAM today. it looks like the auth Attributes will straight forward after all. But since I have not yet implemented it on my side tomorrow around this time I could either
1) implement it  and provide some testvectors
2) implement CMSAuthOutputEncryptor implements OutputEncryptor, MacProvider {} that does the job here.

I would prefere 2) since I plan to swith to the bc implementation once we are done here anyway.

**Comment by wolftobias** [comment] 2019-07-24 07:17
We would also prefer option 2, which should work for our use case. It would be great if you could help us out with the implementation of CMSAuthOutputEncryptor.

**Comment by wolftobias** [comment] 2019-07-24 07:21
After checking our use case we saw that we also don't have a use case for authenticated attributes, we do use only unauthenticated attributes.

**Comment by MadMud** [comment] 2019-07-24 22:21
OK,
I went with option 2) in [my Fork](https://github.com/MadMud/bc-java/tree/CMSAuthEnveloped) and created a PR for visibility (not sure about the traditions around such things here).

Anyway, this adds an AttributeTable as AAD  (see the test for an example) .

Next steps:
1) Expand CMSEnvelopedDataStreamGenerator et. al. to actually create the encoded data and use the CMSAuthOutputEncryptor
2) create a AuthEnvelopedAttributeTableGenerator extends DefaultAuthenticatedAttributeTableGenerator 
3) this is using lightweight interface for now. hopefully jce will not need much copy pasta, as the shared things are analogous to existing logic.

Cheers,
Matthias

**Comment by wolftobias** [comment] 2019-07-25 08:39
We're really exciting about the next steps!

**Comment by wolftobias** [comment] 2019-08-12 09:01
Could we work together to make some progress on encrypting part?

**Comment by MadMud** [comment] 2019-08-12 23:08
Hi Tobias,
Sure! As you see I cannot regularly work on this, only an evening here and there between projects/family/work.
As I said I have actually roughed out the basic non streaming part (streaming is an easy abstraction from, I think). Last time I stopped when junit would not execute the bc test cases already there.

Let me push this part into my fork and let's discuss how to move forward from there.
Cheers,
Matthias

**Comment by MadMud** [comment] 2019-08-13 20:21
Hi Again,
as promised I pushed my work so far to https://github.com/MadMud/bc-java/tree/CMSAuthEnveloped.
Note that the way I implemented it authenveloped is created implicitly when an appropiate cipher is selected. This makes adoption in older code very much straight forward and reuses almost all existing code for the overlap in content. The downside is that the enveloped data code needed to be touch (lightly)...

Tobias, depending on what you need this for perhaps you might want to  either 
* add other KeyTransportRecipients (for testing I did BcRSAKeyTransEnvelopedRecipient)
* add jce classes in addition to the lightweight stuff
* add other AEAD ciphers besides AES/GCM

**Comment by wolftobias** [comment] 2019-08-19 14:02
I've another small issue regarding the signed bouncycastle jar. For testing purpose it is needed to download the whole MadMud tree as a zip, right? 
Is it possible to merge the code MadMud has been written into the master?

**Comment by MadMud** [comment] 2019-08-20 06:02
I think this will not happen. The pull request was denied by the maintenance. It was now decided that extending enveloped data by auth enveloped is not acceptable. 
Anyway, I will not implement another solution just to be shut down by a one sentence mail. This time we need some consensus on how to move forward (if there is interest). If you look back in this thread I tried to establish that months ago but got no answers, so I guess we will have to wait for a while.

PS: for testing purposes I find it convenient to use jdk v12, since sec providers do not need to be signed there.

Cheers,
Matthias

**Comment by bcgit** [comment] 2019-08-20 09:28
Sorry, but we're spread a bit thin. @MadMud I certainly wasn't attempting to discount your efforts, on the other hand I do get to support whatever gets accepted into the future, do that for a while and I think you'll find you get a lot more cautious about how you do things as well.

The current state of things is available at https://www.bouncycastle.org/betas it's not quite complete though. AuthEnvelopedData is sort of between EnvelopedData and AuthenticatedData. The goal at the moment is to have the in-memory model functioning correctly by the time 1.63 comes out. Ideally we would also be able to translate this work over the FIPS versions of the APIs as well as there's no doubt people there could use it too.

**Comment by bcgit** [comment] 2019-08-20 09:30
Basic functionality is shown in org.bouncycastle.cms.test.AuthEnvelopedDataTest

**Comment by MadMud** [comment] 2019-08-20 18:43
Hi,
Yeah, I have been in your place an I totally understand being picky about what you will have to support. If you look back at my earlier messages this was exactly my sentiment.
Thing is, for me to work on this with a positive outcome I will need some input on what you guys have in mind. I think there is just no time for that on your end right now. 

Please keep me in mind when you know how to proceed. I have implemented and integrated this before and would love to contribute my experience.

At the very least you have a source for testvectors now.

Cheers,
MadMud

**Comment by rdoepke** [comment] 2020-08-03 09:25
We just discovered that RFC 5084 seems to have a faulty implementation in Bouncycastle: The message authentication code (MAC) gets appended to the cipher text.

The MAC value therefore can be found twice in the generated ASN.1 structure. It gets both appended to the ciphertext field and set in the dedicated AuthEnvelopedData mac field. The latter one is set and mandatory, as its length in octets must match the aes-ICVlen parameter according to RFC 5084. The fact that the MAC can also be found in the ciphertext field is, however, not explicitly forbidden by the specification, but is at least _unusual_ within DER encoded data, as it being duplicated. I'd therefore interpret the RFC it as it shouldn't be there a second time.

With this ticket being still open, this fact can be observed within the `AuthEnvelopedDataTest`. The `Sample1` CMS structure already contains the duplicate data, as can be seen here: 
http://lapo.it/asn1js/#MIAGCyqGSIb3DQEJEAEXoIAwgAIBADGBmzCBmAIBAoABATANBgkqhkiG9w0BAQEFAASBgG9yJPC3zFmIbPTtSrrTD-71lluua3F1_V_XzzDOczjdymy4tI4sle5HSxJN8yrw-m2JdWKb4s_u4frvmNqE6fcqfFtLpLEMXJneoEWWXZFKbndoqQNRMgfKGCncpeWhktRcSRtbEEk_H4hWggJGmVClS7f_nmCDjwyANBnI3shYMIAGCSqGSIb3DQEHATAfBglghkgBZQMEAQYwEgQQLO0PwnuhYXRk8pLLhgik0aCABB8KvxIkbmBKT73Oz4xtf0DNNGmdn-tzPcOldJUQWCEnAAAAAAQMn-tzPcOldJUQWCEnAAAAAAAA
The MAC (Offset 265) is also appended in the cipher text (Offset 228)

I am currently not sure, if this is an issue with the `org.bouncycastle.crypto.modes.GCMBlockCipher` which appends the MAC to the cipher. However, it is also used outside of CMS contexts. This leads to the impression that CMSAuthEnvelopedDataGenerator should strip it from the encrypted content.

Any thoughts on this?

Regards,
Roland

**Comment by dghgit** [comment] 2021-02-28 03:45
I think this is now resolved. I have working versions for both the lightweight and the JCE APIs and they appear to conform to what is being produced by OpenSSL now. There's still work to be done for handling large messages but I will close this issue as main problem is now "solved". Will show up in 169b03 which should appear on https://www.bouncycastle.org/betas in the next day.

**Closed by dghgit** 2021-02-28 03:45 UTC
