### ISSUE TITLE
Conversion of public key from SW to Montgomery format

### ISSUE THREAD

**Issue by plmn22** [bcgit/bc-java#257] opened 2017-11-21 07:03 UTC
Hi Again, 
Thanks for your previous answer. It was very accurate and also the explanation was great.

But, I have another question:

Now i need to generate X25519 public key. I'm generating that public key, using BC library. When i check the public key that i get from BC, then i can see that it is 64 bytes. According to your explanation I think that BC output it in short-Weierstrass format, while i need it in Montgomery curve format.

How can i convert it to 32 bytes?

This is my java code:

X9ECParameters ecP = CustomNamedCurves.getByName("Curve25519");
this.ECCPointCompressed = true;

ECParameterSpec ecSpec=new ECParameterSpec(ecP.getCurve(), ecP.getG(),ecP.getN(), ecP.getH(), ecP.getSeed());

KeyPairGenerator kpgen;
kpgen = KeyPairGenerator.getInstance("ECDH", "BC");
kpgen.initialize(ecSpec, new SecureRandom());
pairA = kpgen.generateKeyPair();
ECPublicKey eckey = (ECPublicKey)pairA.getPublic();
var public_key = eckey.getQ().getEncoded(true);

The "public_key" returned here is 64 bytes!

Thanks in advance,
Asi Fefer.

**Comment by peterdettman** [comment] 2017-11-29 04:08
Duplicate of question being addressed in #251 .

**Closed by peterdettman** 2017-11-29 04:08 UTC
