### ISSUE TITLE
Certificate verification fails for certain Locales due to locale-sensitive date parsing

### ISSUE THREAD

**Issue by jkakavas** [bcgit/bc-java#405] opened 2018-09-07 10:49 UTC
Hi folk, 

Bouncy Castle uses `SimpleDateFormat` in order to parse the time String it parses out of `org.bouncycastle.asn1.ASN1UTCTime` to a `java.util.Date` object, when performing a validity check for a Certificate.
https://github.com/bcgit/bc-java/blob/119c51069d590d25a77276ba0f56905c28325b7e/prov/src/main/java/org/bouncycastle/jce/provider/X509CertificateObject.java#L138-L151

https://github.com/bcgit/bc-java/blob/119c51069d590d25a77276ba0f56905c28325b7e/prov/src/main/java/org/bouncycastle/jce/provider/X509CertificateObject.java#L219-L222

https://github.com/bcgit/bc-java/blob/a6c3de20781cca2b4c61750eaabe8ba85ed7f3bb/core/src/main/java/org/bouncycastle/asn1/ASN1UTCTime.java#L164-L170

Since `SimpleDateFormat` is [locale-sensitive](https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html), this leads to certificate validation errors for certain locales that follow the Gregorian calendar, but use different epochs , namely [Thai](https://en.wikipedia.org/wiki/Thai_solar_calendar) and [Japanese](https://en.wikipedia.org/wiki/Japanese_calendar)

The dates for the aforementioned locale calendars match day of the month and month (since they follow the Gregorian Calendar), but the year is off.

The following minimal example test replicates the issue:

```java
import org.bouncycastle.jce.provider.BouncyCastleProvider;

import java.io.FileInputStream;
import java.io.InputStream;
import java.security.Security;
import java.security.cert.CertificateFactory;
import java.security.cert.X509Certificate;
import java.text.DateFormat;
import java.util.Locale;

public class Main {

    public static void main(String[] args) throws Exception {
        Security.addProvider(new BouncyCastleProvider());
        Locale list[] = DateFormat.getAvailableLocales();
        for (Locale l : list){
            InputStream in = new FileInputStream("certificate.pem");
            Locale.setDefault(l);
            CertificateFactory factory = CertificateFactory.getInstance("X.509");
            X509Certificate cert = (X509Certificate) factory.generateCertificate(in);
            try {
                cert.checkValidity();
            }catch (Exception cee){
                System.out.println("Default failed for locale "+l);
                System.out.println(cee.getMessage());
            }
            in = new FileInputStream("testclient.crt");
            CertificateFactory BouncyCastleFactory = CertificateFactory.getInstance("X.509", "BC");
            X509Certificate certB = (X509Certificate) BouncyCastleFactory.generateCertificate(in);
            try {
                certB.checkValidity();
            }catch (Exception cee){
                System.out.println("BouncyCastle failed for locale "+l);
                System.out.println(cee.getMessage());
            }
        }

    }
}
```

with the following output

```
BouncyCastle failed for locale ja_JP_JP_#u-ca-japanese
certificate not valid till 20150923185255GMT+00:00
BouncyCastle failed for locale th_TH
certificate expired on 20190922185255GMT+00:00
BouncyCastle failed for locale th_TH_TH_#u-nu-thai
certificate expired on 20190922185255GMT+00:00
```

Note that the expiry dates are printed in a local unaware manner (as these were parsed from `ASN1UTCTime` )

**Comment by bcgit** [comment] 2018-09-30 05:32
Thanks for the report. I think we now have a way of dealing with this that is "portable" across VMs... all I'll say is it wasn't fun... any way, the update is now available at https://downloads.bouncycastle.org/betas/

let us know how it goes.

**Comment by jkakavas** [comment] 2018-10-18 10:16
We are not able to try and verify this until the change makes it through to a FIPS version of the BouncyCastle provider, as this is the only one we test against. Feel free to close this issue at will, thanks for taking the time to address the issue !

**Comment by seut** [comment] 2021-03-18 16:54
jftr: I just came across this issue while using generated self-signed certificates which also fails for some locales due to the same root cause.

Example stacktrace when using the `ks` (Kashmiri) locale:
```
Caused by: java.lang.IllegalArgumentException: invalid date string: Unparseable date: "òððóñøñòôõóóGMT+00:00"
        at org.bouncycastle.asn1.ASN1UTCTime.<init>(ASN1UTCTime.java:115)
        at org.bouncycastle.asn1.DERUTCTime.<init>(Unknown Source)
        at org.bouncycastle.asn1.x509.Time.<init>(Unknown Source)
        at org.bouncycastle.cert.X509v3CertificateBuilder.<init>(Unknown Source)
        at org.bouncycastle.cert.jcajce.JcaX509v3CertificateBuilder.<init>(Unknown Source)
        at io.netty.handler.ssl.util.BouncyCastleSelfSignedCertGenerator.generate(BouncyCastleSelfSignedCertGenerator.java:52)
        at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:246)
```

Happened with bcpkix-jdk15on v1.68.

**Comment by dghgit** [comment] 2021-05-30 06:48
Closing as this was also fixed in BC-FJA 1.0.2.

**Closed by dghgit** 2021-05-30 06:48 UTC
