### ISSUE TITLE
MLDSA2 error

### ISSUE THREAD

**Issue by jjzl** [bcgit/bc-java#1918] opened 2024-11-21 01:56 UTC
Hello everyone, could someone help me with this error that appears when I try to create a hybrid certificate with version 1.79?

Exception in thread "main" java.lang.IllegalArgumentException: unknown parameter name: MLDSA2
at org.bouncycastle.jcajce.spec.MLDSAParameterSpec.fromName(Unknown Source)

Many thanks

**Comment by peterdettman** [comment] 2024-11-21 07:39
Obviously "MLDSA2" is not a recognized name for an MLDSAParameterSpec (perhaps "ML-DSA-44" was intended?). Please show the code for "try to create a hybrid certificate" and/or show a longer stack trace for the exception.

**Comment by dghgit** [comment] 2024-11-24 07:06
Sorry, it's a typo in a related kotlin script see [bc-kotlin/issues #16](https://github.com/bcgit/bc-kotlin/issues/16). It's now fixed on GitHub.

**Closed by dghgit** 2024-11-24 07:06 UTC
