### ISSUE TITLE
PKIXNameConstraintValidator NPEs on OtherName  

### ISSUE THREAD

**Issue by KyleBS** [bcgit/bc-java#594] opened 2019-09-20 16:32 UTC
The intersectOtherName method of PKIXNameConstraintValidator appears to fail to to account for null input:

https://github.com/bcgit/bc-java/blob/master/core/src/main/java/org/bouncycastle/asn1/x509/PKIXNameConstraintValidator.java#L511-L518

The next intersection down, intersectEmail, however does:

https://github.com/bcgit/bc-java/blob/master/core/src/main/java/org/bouncycastle/asn1/x509/PKIXNameConstraintValidator.java#L530-L557

In practice, this results in intersectPermittedSubtree throwing NPEs whenever a GeneralSubtree containing a OtherName GeneralName is supplied.

**Comment by bcgit** [comment] 2019-09-30 06:30
I think this is now fixed.

**Closed by bcgit** 2019-09-30 06:30 UTC

**Comment by KyleBS** [comment] 2019-09-30 10:07
Great! Mind linking where this was fixed?

**Comment by bcgit** [comment] 2019-09-30 18:45
It's now in the current beta: https://www.bouncycastle.org/betas github should update sometime today as well.

**Comment by KyleBS** [comment] 2019-10-01 11:04
Pulled the latest beta (164b05) to check it out, not seeing a behavior change:

```
import org.bouncycastle.asn1.ASN1ObjectIdentifier;
import org.bouncycastle.asn1.DERNull;
import org.bouncycastle.asn1.x509.*;

public class Main {

    public static void main(final String[] args) {
        GeneralName name = new GeneralName(GeneralName.otherName, new OtherName(new ASN1ObjectIdentifier("1.1"), DERNull.INSTANCE));
        GeneralSubtree subtree = new GeneralSubtree(name);

        PKIXNameConstraintValidator validator = new PKIXNameConstraintValidator();
        validator.intersectPermittedSubtree(subtree);
    }
}
```
yields: 

```
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.util.HashSet.<init>(HashSet.java:119)
        at org.bouncycastle.asn1.x509.PKIXNameConstraintValidator.intersectOtherName(PKIXNameConstraintValidator.java:513)
        at org.bouncycastle.asn1.x509.PKIXNameConstraintValidator.intersectPermittedSubtree(PKIXNameConstraintValidator.java:169)
        at org.bouncycastle.asn1.x509.PKIXNameConstraintValidator.intersectPermittedSubtree(PKIXNameConstraintValidator.java:135)
        at Main.main(Main.java:12)
```

Not seeing any commits that seem relevant in the github mirror or upstream git repo. Any chance this didn't get committed?

**Comment by bcgit** [comment] 2019-10-02 11:24
Hmmmm... try 164b06 - not sure what happened with 164b05, but 06 passes the example

**Comment by KyleBS** [comment] 2019-10-02 12:42
Sure enough, 164b06 works for me as well. Thanks again!

**Comment by bbernier** [comment] 2019-10-16 21:01
Hello, this issue seems to be resolved, but now there is an unexpected ClassCastException happening. Still related to PKIXNameConstraintsValidator on OtherName

`import org.bouncycastle.asn1.*;
import org.bouncycastle.asn1.x509.*;
import org.bouncycastle.jce.provider.*;
import org.bouncycastle.jce.provider.PKIXNameConstraintValidator;

public class Maine {
    public static void main(final String[] args) {
        GeneralName name = new GeneralName(GeneralName.otherName, new org.bouncycastle.asn1.x509.OtherName(new ASN1ObjectIdentifier("1.1"), DERNull.INSTANCE));
        GeneralSubtree subtree = new GeneralSubtree(name);

        PKIXNameConstraintValidator validator = new PKIXNameConstraintValidator();
        validator.intersectPermittedSubtree(subtree);
        validator.addExcludedSubtree(subtree);

        try {
            validator.checkExcluded(name);
        } catch (PKIXNameConstraintValidatorException e) {
            e.printStackTrace();
        }

        try{
            validator.checkPermitted(name);
        } catch (PKIXNameConstraintValidatorException e) {
            e.printStackTrace();
        }
    }
}
`

Results in:

`org.bouncycastle.jce.provider.PKIXNameConstraintValidatorException: OtherName is from an excluded subtree.
	at org.bouncycastle.jce.provider.PKIXNameConstraintValidator.checkExcluded(Unknown Source)
	at Main.main(Main.java:18)
Caused by: org.bouncycastle.asn1.x509.NameConstraintValidatorException: OtherName is from an excluded subtree.
	at org.bouncycastle.asn1.x509.PKIXNameConstraintValidator.checkExcludedOtherName(Unknown Source)
	at org.bouncycastle.asn1.x509.PKIXNameConstraintValidator.checkExcluded(Unknown Source)
	... 2 more
Exception in thread "main" java.lang.ClassCastException: org.bouncycastle.asn1.x509.GeneralSubtree cannot be cast to org.bouncycastle.asn1.x509.OtherName
	at org.bouncycastle.asn1.x509.PKIXNameConstraintValidator.checkPermittedOtherName(Unknown Source)
	at org.bouncycastle.asn1.x509.PKIXNameConstraintValidator.checkPermitted(Unknown Source)
	at org.bouncycastle.jce.provider.PKIXNameConstraintValidator.checkPermitted(Unknown Source)
	at Main.main(Main.java:24)`

It appears as though checkExcludedNameConstraints appropriately calls OtherName.getInstance, however checkPermittedNameConstraints inappropriately casts resulting in this issue:

https://github.com/bcgit/bc-java/blob/master/core/src/main/java/org/bouncycastle/asn1/x509/PKIXNameConstraintValidator.java#L856-L892

**Comment by bbernier** [comment] 2019-10-24 14:03
Cut https://github.com/bcgit/bc-java/issues/613 for the above comment.
