### ISSUE TITLE
NPE from various locations in Argon2BytesGenerator when used with JBoss 7

### ISSUE THREAD

**Issue by jls-pentasys** [bcgit/bc-java#741] opened 2020-06-26 06:22 UTC
I am attempting to use Bouncy Castle's Argon2 crypto functionality, but will randomly receive NPEs from Argon2BytesGenerator. 

My Argon2Parameters are:

```Java
Argon2Parameters.Builder(Argon2Parameters.ARGON2_id).
.withVersion(ARGON2_VERSION_13)
.withMemoryAsKB(32768)
.withIterations(3)
.withParallelism(4)
.withSalt(salt)
.build()
```

Here are two examples of the NPEs:

```
at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
at org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation( CurrentInvocationContextInterceptor.java:41)
at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
at org.jboss.as.ejb3.component.interceptors.ShutDownInterceptorFactory$1.processInvocation(ShutDownInterceptorFactory.java:64)
at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
at org.jboss.as.ejb3.component.interceptors.LoggingInterceptor.processInvocation(LoggingInterceptor.java:59)
at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
at org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50)
at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
at org.jboss.as.ejb3.component.interceptors.AdditionalSetupInterceptor.processInvocation(AdditionalSetupInterceptor.java:65) 
at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288) 
at org.jboss.as.ee.component.TCCLInterceptor.processInvocation(TCCLInterceptor.java:45)
at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)
at org.jboss.as.ee.component.ViewService$View.invoke(ViewService.java:165)
at org.jboss.as.ejb3.remote.protocol.versionone.MethodInvocationMessageHandler.invokeMethod( MethodInvocationMessageHandler.java:321)
at org.jboss.as.ejb3.remote.protocol.versionone.MethodInvocationMessageHandler.access$100( MethodInvocationMessageHandler.java:69)
at org.jboss.as.ejb3.remote.protocol.versionone.MethodInvocationMessageHandler$1.run(MethodInvocationMessageHandler.java:202)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
at java.lang.Thread.run(Thread.java:748)
at org.jboss.threads.JBossThread.run(JBossThread.java:122)
Caused by: java.lang.NullPointerException
at org.bouncycastle.crypto.generators.Argon2BytesGenerator.reset(Unknown Source)
at org.bouncycastle.crypto.generators.Argon2BytesGenerator.generateBytes(Unknown Source)
at org.bouncycastle.crypto.generators.Argon2BytesGenerator.generateBytes(Unknown Source)
at org.bouncycastle.crypto.generators.Argon2BytesGenerator.generateBytes(Unknown Source)
at com.example.login.password.ArgonPasswordService.match(ArgonPasswordService.java:115)
at com.example.login.password.ArgonPasswordService$Proxy$_$$_WeldSubclass.match( ArgonPasswordService$Proxy$_$$_WeldSubclass.java)
at sun.reflect.GeneratedMethodAccessor685.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.jboss.weld.interceptor.proxy.SimpleInterceptionChain.invokeNextInterceptor(SimpleInterceptionChain.java:85)
at org.jboss.weld.interceptor.proxy.InterceptorInvocationContext.proceed(InterceptorInvocationContext.java:127)
at com.example.service.aop.LoggedInterceptor.logMethod(LoggedInterceptor.java:40)
at sun.reflect.GeneratedMethodAccessor207.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.jboss.weld.interceptor.proxy.SimpleMethodInvocation.invoke(SimpleMethodInvocation.java:30)
at org.jboss.weld.interceptor.proxy.SimpleInterceptionChain.invokeNextInterceptor(SimpleInterceptionChain.java:69)
at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:112)
at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:88)
at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(
... Truncated. 71.2871287129% shown.
```

and

```
at org.jboss.as.weld.ejb.Jsr299BindingsInterceptor.delegateInterception(Jsr299BindingsInterceptor.java:114)
at org.jboss.as.weld.ejb.Jsr299BindingsInterceptor.doMethodInterception(Jsr299BindingsInterceptor.java:127)
at org.jboss.as.weld.ejb.Jsr299BindingsInterceptor.processInvocation(Jsr299BindingsInterceptor.java:137)
at org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:58)
at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
at org.jboss.invocation.WeavedInterceptor.processInvocation(WeavedInterceptor.java:53)
at org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:58)
at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
at org.jboss.as.ejb3.component.invocationmetrics.ExecutionTimeInterceptor.processInvocation(ExecutionTimeInterceptor.java:43)
at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
at org.jboss.as.jpa.interceptor.SBInvocationInterceptor.processInvocation(SBInvocationInterceptor.java:47)
at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
at org.jboss.as.weld.ejb.EjbRequestScopeActivationInterceptor.processInvocation(EjbRequestScopeActivationInterceptor.java:94)
at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
at org.jboss.invocation.InitialInterceptor.processInvocation(InitialInterceptor.java:21)
at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)
at org.jboss.as.ee.component.interceptors.ComponentDispatcherInterceptor.processInvocation( ComponentDispatcherInterceptor.java:53)
at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
at org.jboss.as.ejb3.component.pool.PooledInstanceInterceptor.processInvocation(PooledInstanceInterceptor.java:51)
at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:248)
at org.jboss.as.ejb3.tx.CMTTxInterceptor.required(CMTTxInterceptor.java:315)
at org.jboss.as.ejb3.tx.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:214)
at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
at org.jboss.as.ejb3.remote.EJBRemoteTransactionPropagatingInterceptor.processInvocation( EJBRemoteTransactionPropagatingInterceptor.java:79)
at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
at org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation( CurrentInvocationContextInterceptor.java:41)
at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
at org.jboss.as.ejb3.component.interceptors.ShutDownInterceptorFactory$1.processInvocation(ShutDownInterceptorFactory.java:64)
at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
at org.jboss.as.ejb3.component.interceptors.LoggingInterceptor.processInvocation(LoggingInterceptor.java:59)
at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
at org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50)
at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
at org.jboss.as.ejb3.component.interceptors.AdditionalSetupInterceptor.processInvocation(AdditionalSetupInterceptor.java:65)
at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
at org.jboss.as.ee.component.TCCLInterceptor.processInvocation(TCCLInterceptor.java:45)
at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)
at org.jboss.as.ee.component.ViewService$View.invoke(ViewService.java:165)
at org.jboss.as.ejb3.remote.protocol.versionone.MethodInvocationMessageHandler.invokeMethod( MethodInvocationMessageHandler.java:321)
at org.jboss.as.ejb3.remote.protocol.versionone.MethodInvocationMessageHandler.access$100( MethodInvocationMessageHandler.java:69)
at org.jboss.as.ejb3.remote.protocol.versionone.MethodInvocationMessageHandler$1.run(MethodInvocationMessageHandler.java:202)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
at java.lang.Thread.run(Thread.java:748)
at org.jboss.threads.JBossThread.run(JBossThread.java:122)
Caused by: java.lang.NullPointerException
at org.bouncycastle.crypto.generators.Argon2BytesGenerator$Block.access$400(Unknown Source)
at org.bouncycastle.crypto.generators.Argon2BytesGenerator.getPseudoRandom(Unknown Source)
at org.bouncycastle.crypto.generators.Argon2BytesGenerator.fillSegment(Unknown Source)
at org.bouncycastle.crypto.generators.Argon2BytesGenerator.fillMemoryBlocks(Unknown Source)
at org.bouncycastle.crypto.generators.Argon2BytesGenerator.generateBytes(Unknown Source)
at org.bouncycastle.crypto.generators.Argon2BytesGenerator.generateBytes(Unknown Source)
at org.bouncycastle.crypto.generators.Argon2BytesGenerator.generateBytes(Unknown Source)
at com.example.service.login.password.ArgonPasswordService.match(ArgonPasswordService.java:115)
at com.example.service.login.password.ArgonPasswordService$Proxy$_$$_WeldSubclass.match( ArgonPasswordService$Proxy$_$$_WeldSubclass.java)
at sun.reflect.GeneratedMethodAccessor476.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:607)
at org.jboss.weld.interceptor.proxy.SimpleInterceptionChain.invokeNextInterceptor(SimpleInterceptionChain.java:85)
at org.jboss.weld.interceptor.proxy.InterceptorInvocationContext.proceed(InterceptorInvocationContext.java:127)
at com.example.service.aop.LoggedInterceptor.logMethod(LoggedInterceptor.java:40)
at sun.reflect.GeneratedMethodAccessor202.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:607)
at org.jboss.weld.interceptor.proxy.SimpleMethodInvocation.invoke(SimpleMethodInvocation.java:30)
at org.jboss.weld.interceptor.proxy.SimpleInterceptionChain.invokeNextInterceptor(SimpleInterceptionChain.java:69)
... Truncated. 71.2871287129% shown.
```

Any help on what is causing this would be greatly appreciated.

Thanks in advance.

**Comment by peterdettman** [comment] 2020-06-26 10:33
Thanks for reporting. Presumably this is related to repeated generateBytes calls. We've found and fixed some NPEs we found that look like the above. If you need a short-term workaround, you could create and init a new Argon2BytesGenerator for each generateBytes call.

**Comment by jls-pentasys** [comment] 2020-06-26 13:38
Hey Peter,
Thanks for the workaround, it's working so far. I have a few other stacktrackes with NPEs coming from other sources. Would it help if I included them as well?

**Comment by peterdettman** [comment] 2020-06-27 05:56
It wouldn't hurt to include any other stack traces you have so we can check them. We have a new release coming out any day now, so best to fix all we can.

**Comment by esistegalaber** [comment] 2020-06-30 05:46
Hey Peter,
Found this one, maybe it help.

at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:122)
Caused by: java.lang.NullPointerException
	at org.bouncycastle.crypto.generators.Argon2BytesGenerator.fillFirstBlocks(Unknown Source)
	at org.bouncycastle.crypto.generators.Argon2BytesGenerator.initialize(Unknown Source)
	at org.bouncycastle.crypto.generators.Argon2BytesGenerator.generateBytes(Unknown Source)
	at org.bouncycastle.crypto.generators.Argon2BytesGenerator.generateBytes(Unknown Source)
	at org.bouncycastle.crypto.generators.Argon2BytesGenerator.generateBytes(Unknown Source)
	at de.o2.piranha.service.login.password.ArgonPasswordService.match(ArgonPasswordService.java:115)
	at de.o2.piranha.service.login.password.ArgonPasswordService$Proxy$_$$_WeldSubclass.match(ArgonPasswordService$Proxy$_$$_WeldSubclass.java)
	at sun.reflect.GeneratedMethodAccessor376.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.weld.interceptor.proxy.SimpleInterceptionChain.invokeNextInterceptor(SimpleInterceptionChain.java:85)
	at org.jboss.weld.interceptor.proxy.InterceptorInvocationContext.proceed(InterceptorInvocationContext.java:127)
	at de.o2.piranha.service.aop.LoggedInterceptor.logMethod(LoggedInterceptor.java:40)
	at sun.reflect.GeneratedMethodAccessor208.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

**Comment by esistegalaber** [comment] 2020-06-30 05:47
And another one:

Caused by: java.lang.NullPointerException
	at org.bouncycastle.crypto.generators.Argon2BytesGenerator$Block.xor(Unknown Source)
	at org.bouncycastle.crypto.generators.Argon2BytesGenerator$Block.access$800(Unknown Source)
	at org.bouncycastle.crypto.generators.Argon2BytesGenerator$FillBlock.fillBlock(Unknown Source)
	at org.bouncycastle.crypto.generators.Argon2BytesGenerator$FillBlock.access$300(Unknown Source)
	at org.bouncycastle.crypto.generators.Argon2BytesGenerator.fillSegment(Unknown Source)
	at org.bouncycastle.crypto.generators.Argon2BytesGenerator.fillMemoryBlocks(Unknown Source)
	at org.bouncycastle.crypto.generators.Argon2BytesGenerator.generateBytes(Unknown Source)
	at org.bouncycastle.crypto.generators.Argon2BytesGenerator.generateBytes(Unknown Source)
	at org.bouncycastle.crypto.generators.Argon2BytesGenerator.generateBytes(Unknown Source)
	at de.o2.piranha.service.login.password.ArgonPasswordService.match(ArgonPasswordService.java:115)
	at de.o2.piranha.service.login.password.ArgonPasswordService$Proxy$_$$_WeldSubclass.match(ArgonPasswordService$Proxy$_$$_WeldSubclass.java)
	at sun.reflect.GeneratedMethodAccessor376.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.weld.interceptor.proxy.SimpleInterceptionChain.invokeNextInterceptor(SimpleInterceptionChain.java:85)
	at org.jboss.weld.interceptor.proxy.InterceptorInvocationContext.proceed(InterceptorInvocationContext.java:127)
	at de.o2.piranha.service.aop.LoggedInterceptor.logMethod(LoggedInterceptor.java:40)
	at sun.reflect.GeneratedMethodAccessor208.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.weld.interceptor.proxy.SimpleMethodInvocation.invoke(SimpleMethodInvocation.java:30)
	at org.jboss.weld.interceptor.proxy.SimpleInterceptionChain.invokeNextInterceptor(SimpleInterceptionChain.java:69)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:112)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:88)
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:55)
	at de.o2.piranha.service.login.password.ArgonPasswordService$Proxy$_$$_WeldSubclass.match(ArgonPasswordService$Proxy$_$$_WeldSubclass.java)
	at de.o2.piranha.service.login.PasswordService.isPasswordCorrect(PasswordService.java:119)
	at de.o2.piranha.service.login.PasswordService$Proxy$_$$_WeldSubclass.isPasswordCorrect(PasswordService$Proxy$_$$_WeldSubclass.java)
	at sun.reflect.GeneratedMethodAccessor257.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.weld.interceptor.proxy.SimpleInterceptionChain.invokeNextInterceptor(SimpleInterceptionChain.java:85)
	at org.jboss.weld.interceptor.proxy.InterceptorInvocationContext.proceed(InterceptorInvocationContext.java:127)
	at de.o2.piranha.service.aop.LoggedInterceptor.logMethod(LoggedInterceptor.java:40)
	at sun.reflect.GeneratedMethodAccessor208.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

**Comment by esistegalaber** [comment] 2020-06-30 05:48
@peterdettman Thanks a lot for the workaround, seems to work like a charm and saved my day (or rather my weekend).
BR

**Comment by peterdettman** [comment] 2020-07-09 05:05
@jls-pentasys @esistegalaber Release 1.66 is now out, please confirm (or not) that it fixes the NPEs you were seeing.

**Comment by dghgit** [comment] 2020-10-28 08:40
Closing, assumed resolved.

**Closed by dghgit** 2020-10-28 08:40 UTC
