### ISSUE TITLE
Java 13 (I know...) Compatibility - XDH Key Generation (Works on Java 12)

### ISSUE THREAD

**Issue by brcolow** [bcgit/bc-java#589] opened 2019-09-11 23:31 UTC
I am not sure if this has anything to do with Bouncycastle. Java 13 has JEP 353 which rewrites (parts) of the legacy socket API. I am using Bouncycastle 1.62.

When I try to connect to Amazon AWS DynamoDB on Java 13, I get the following (partial) stack trace:

```
Caused by: java.lang.RuntimeException: Could not generate XDH keypair
at java.base/sun.security.ssl.XDHKeyExchange$XDHEPossession.<init>(XDHKeyExchange.java:110)
at java.base/sun.security.ssl.NamedGroup$XDHFunctions.createPossession(NamedGroup.java:750)
at java.base/sun.security.ssl.NamedGroup.createPossession(NamedGroup.java:390)
at java.base/sun.security.ssl.SSLKeyExchange$T13KeyAgreement.createPossession(SSLKeyExchange.java:568)
at java.base/sun.security.ssl.SSLKeyExchange.createPossessions(SSLKeyExchange.java:84)
at java.base/sun.security.ssl.KeyShareExtension$CHKeyShareProducer.produce(KeyShareExtension.java:255)
at java.base/sun.security.ssl.SSLExtension.produce(SSLExtension.java:571)
at java.base/sun.security.ssl.SSLExtensions.produce(SSLExtensions.java:250)
at java.base/sun.security.ssl.ClientHello$ClientHelloKickstartProducer.produce(ClientHello.java:649)
at java.base/sun.security.ssl.SSLHandshake.kickstart(SSLHandshake.java:519)
at java.base/sun.security.ssl.ClientHandshakeContext.kickstart(ClientHandshakeContext.java:107)
at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:231)
at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:430)
... 61 more
Caused by: java.security.InvalidAlgorithmParameterException: invalid parameterSpec: java.security.spec.NamedParameterSpec@15e0fe05
at org.bouncycastle.jcajce.provider.asymmetric.edec.KeyPairGeneratorSpi.initialize(Unknown Source)
at java.base/java.security.KeyPairGenerator$Delegate.initialize(KeyPairGenerator.java:699)
at java.base/sun.security.ssl.XDHKeyExchange$XDHEPossession.<init>(XDHKeyExchange.java:105)
... 73 more
```

Downgrading to the latest nightly build of the Java 12 repository makes the error go away.

The actual chain of events here is that the Amazon AWS SDK is calling Apache's HTTP client which is trying to make an SSL connection. I am not 100% sure how Bouncycastle comes into it unless the only XDH provider accessible is Bouncycastle? I tried to put the provider at position 2, but it made no difference.

I believe the full stack trace where a custom AWS Lambda runtime calls a Lambda request handler, calls DynamoDB, calls Apache, calls, etc. etc. is essentially obfuscation. I think this would show up trying to make an SSL connection to Amazon's DynamoDB server that happens to use XDH key exchange. I see some changes to the `sun.security.ssl.SSLSocketImpl` classes (as well as other classes in the stack trace) new to Java 13 (most likely related to the aforementioned JEP).

This could very well be a bug in the new Java socket implementation and if so I will certainly open this upstream.

Thanks for your time.

**Comment by brcolow** [comment] 2019-09-11 23:33
<details>
   <summary>Click to expand (Full Stack Trace)</summary>

```
        Caused by: javax.net.ssl.SSLException: Could not generate XDH keypair
at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:324)
at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:267)
at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:262)
at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1652)
at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:443)
at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
at software.amazon.awssdk.http.apache.internal.conn.SdkTlsSocketFactory.connectSocket(SdkTlsSocketFactory.java:113)
at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at software.amazon.awssdk.http.apache.internal.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:80)
at com.sun.proxy.$Proxy5.connect(Unknown Source)
at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
at software.amazon.awssdk.http.apache.internal.impl.ApacheSdkHttpClient.execute(ApacheSdkHttpClient.java:72)
at software.amazon.awssdk.http.apache.ApacheHttpClient.execute(ApacheHttpClient.java:240)
at software.amazon.awssdk.http.apache.ApacheHttpClient.access$500(ApacheHttpClient.java:106)
at software.amazon.awssdk.http.apache.ApacheHttpClient$1.call(ApacheHttpClient.java:221)
at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.executeHttpRequest(MakeHttpRequestStage.java:66)
at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:51)
at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:35)
at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:64)
at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:36)
at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:77)
at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:39)
at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.doExecute(RetryableStage.java:113)
at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.execute(RetryableStage.java:86)
... 27 more
Caused by: java.lang.RuntimeException: Could not generate XDH keypair
at java.base/sun.security.ssl.XDHKeyExchange$XDHEPossession.<init>(XDHKeyExchange.java:110)
at java.base/sun.security.ssl.NamedGroup$XDHFunctions.createPossession(NamedGroup.java:750)
at java.base/sun.security.ssl.NamedGroup.createPossession(NamedGroup.java:390)
at java.base/sun.security.ssl.SSLKeyExchange$T13KeyAgreement.createPossession(SSLKeyExchange.java:568)
at java.base/sun.security.ssl.SSLKeyExchange.createPossessions(SSLKeyExchange.java:84)
at java.base/sun.security.ssl.KeyShareExtension$CHKeyShareProducer.produce(KeyShareExtension.java:255)
at java.base/sun.security.ssl.SSLExtension.produce(SSLExtension.java:571)
at java.base/sun.security.ssl.SSLExtensions.produce(SSLExtensions.java:250)
at java.base/sun.security.ssl.ClientHello$ClientHelloKickstartProducer.produce(ClientHello.java:649)
at java.base/sun.security.ssl.SSLHandshake.kickstart(SSLHandshake.java:519)
at java.base/sun.security.ssl.ClientHandshakeContext.kickstart(ClientHandshakeContext.java:107)
at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:231)
at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:430)
... 61 more
Caused by: java.security.InvalidAlgorithmParameterException: invalid parameterSpec: java.security.spec.NamedParameterSpec@7318daf8
at org.bouncycastle.jcajce.provider.asymmetric.edec.KeyPairGeneratorSpi.initialize(Unknown Source)
at java.base/java.security.KeyPairGenerator$Delegate.initialize(KeyPairGenerator.java:699)
at java.base/sun.security.ssl.XDHKeyExchange$XDHEPossession.<init>(XDHKeyExchange.java:105)
... 73 more
    ```
    </detail

**Comment by brcolow** [comment] 2019-09-27 18:18
The workaround ` jdk.tls.namedGroups="secp256r1, secp384r1, ffdhe2048, ffdhe3072"` does not seem to work. I will try lowering the priority to below 2.

**Comment by brcolow** [comment] 2019-09-27 18:23
Even with:

```java
    static {
        if (Security.getProvider(BouncyCastleProvider.PROVIDER_NAME) == null) {
            int requestedPosition = 2;
            int actualPosition = Security.insertProviderAt(new BouncyCastleProvider(), 9999);
            System.out.println("Requested to add BouncyCastleProvider at position: " + requestedPosition +
                    " and was actually added at position: " + actualPosition);
        }
    }
```

The Bouncycastle provider is still being called and the same error is resulting.

**Comment by brcolow** [comment] 2019-10-02 21:54
The `System.setProperty("jdk.tls.namedGroups", "secp256r1, secp384r1, ffdhe2048, ffdhe3072");` work-around does indeed work.

**Comment by peterdettman** [comment] 2019-10-03 05:27
OK, glad that's working. Moving the provider to **after SunEC provider** should also work; the code snippet shown above does not convince me that you tested this properly.

**Comment by brcolow** [comment] 2019-10-03 17:25
Is there a way to query what "slot" the SunEC provider is in to make sure that BouncyCastle is after that number?

**Comment by peterdettman** [comment] 2019-10-04 06:33
Well you can see the list in your java.security config file, and even install BC that way. If it has to be programmatic, then look at the other methods available on java.security.Security class, in particular the getProviders method will return all installed providers "in their preference order".

**Comment by bcgit** [comment] 2019-10-06 03:37
Okay, I think this is now fixed, I've added handling of any algorithm parameter spec that has a getName() method.

**Comment by SamuelPadou** [comment] 2019-10-18 14:23
Hi, using 1.64 I have the following exception:

```
Caused by: java.lang.ClassCastException: class org.bouncycastle.jcajce.provider.asymmetric.edec.BCXDHPublicKey cannot be cast to class java.security.interfaces.XECPublicKey (org.bouncycastle.jcajce.provider.asymmetric.edec.BCXDHPublicKey is in unnamed module of loader 'app'; java.security.interfaces.XECPublicKey is in module java.base of loader 'bootstrap')
	at java.base/sun.security.ssl.XDHKeyExchange$XDHEPossession.<init>(XDHKeyExchange.java:108)
	at java.base/sun.security.ssl.NamedGroup$XDHFunctions.createPossession(NamedGroup.java:750)
	at java.base/sun.security.ssl.NamedGroup.createPossession(NamedGroup.java:390)
	at java.base/sun.security.ssl.SSLKeyExchange$T13KeyAgreement.createPossession(SSLKeyExchange.java:568)
	at java.base/sun.security.ssl.SSLKeyExchange.createPossessions(SSLKeyExchange.java:84)
	at java.base/sun.security.ssl.KeyShareExtension$CHKeyShareProducer.produce(KeyShareExtension.java:255)
	at java.base/sun.security.ssl.SSLExtension.produce(SSLExtension.java:571)
	at java.base/sun.security.ssl.SSLExtensions.produce(SSLExtensions.java:250)
	at java.base/sun.security.ssl.ClientHello$ClientHelloKickstartProducer.produce(ClientHello.java:649)
	at java.base/sun.security.ssl.SSLHandshake.kickstart(SSLHandshake.java:519)
	at java.base/sun.security.ssl.ClientHandshakeContext.kickstart(ClientHandshakeContext.java:107)
	at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:231)
	at java.base/sun.security.ssl.SSLEngineImpl.beginHandshake(SSLEngineImpl.java:107)
	... 1 more
```
Look like the key exchange implementation expect a XECPublicKey interface for the public key.

**Comment by brcolow** [comment] 2019-10-18 16:40
@SamuelPadou I don't think that is related to this issue.

**Comment by SamuelPadou** [comment] 2019-10-18 21:29
It's not exactly the same error but it seem related. It is also linked to the added support for X25519 and X448 by JDK-8171279 in the JDK13 build.

The fix above in 1.64 correct the exception in the KeyPairGenerator initialisation, but this other exception occurs 2 lines after when the XDHEPossession try to cast the public key to XECPublicKey. This interface was also introduced in JDK 11 and it look like BC doesn't support it either. 

I'll do some more tests and open another issue if this isn't related to this one.

**Comment by brcolow** [comment] 2020-01-22 19:13
@spadou You are indeed correct that it is related.

**Comment by bcgit** [comment] 2020-03-18 07:31
I think this one might also be fixed in the latest beta. https://www.bouncycastle.org/betas

**Comment by dghgit** [comment] 2020-10-31 01:21
Closing as fixed.

**Closed by dghgit** 2020-10-31 01:21 UTC

**Comment by wei-kumar** [comment] 2021-02-12 18:26
I am using JDK11.0.10,  my BC-168 still hit this same issue. 
I noticed that the case was closed on Oct 30, 2020.
BC-168 made available on 12/21/2020. I would expect the fix should in this BC-168 but apparently it is not.

Please look into this issue.

**Comment by jbakermk** [comment] 2021-02-12 20:50
Just tested with Tomcat 9, Java 15 and bc 1.68: 

```
2-Feb-2021 20:49:39.067 SEVERE [https-jsse-nio-8443-exec-9] org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun Error running socket processor
        java.lang.ClassCastException: class org.bouncycastle.jcajce.provider.asymmetric.edec.BCXDHPublicKey cannot be cast to class java.security.interfaces.XECPublicKey (org.bouncycastle.jcajce.provider.asymmetric.edec.BCXDHPublicKey is in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @55e8ec2f; java.security.interfaces.XECPublicKey is in module java.base of loader 'bootstrap')
                at java.base/sun.security.ssl.XDHKeyExchange$XDHEPossession.<init>(XDHKeyExchange.java:107)
                at java.base/sun.security.ssl.NamedGroup$XDHScheme.createPossession(NamedGroup.java:661)
                at java.base/sun.security.ssl.NamedGroup$NamedGroupSpec.createPossession(NamedGroup.java:543)
                at java.base/sun.security.ssl.NamedGroup.createPossession(NamedGroup.java:431)
                at java.base/sun.security.ssl.SSLKeyExchange$T13KeyAgreement.createPossession(SSLKeyExchange.java:568)
                at java.base/sun.security.ssl.SSLKeyExchange.createPossessions(SSLKeyExchange.java:84)
                at java.base/sun.security.ssl.KeyShareExtension$SHKeyShareProducer.produce(KeyShareExtension.java:545)
                at java.base/sun.security.ssl.SSLExtension.produce(SSLExtension.java:603)
                at java.base/sun.security.ssl.SSLExtensions.produce(SSLExtensions.java:253)
                at java.base/sun.security.ssl.ServerHello$T13ServerHelloProducer.produce(ServerHello.java:587)
                at java.base/sun.security.ssl.SSLHandshake.produce(SSLHandshake.java:440)
                at java.base/sun.security.ssl.ClientHello$T13ClientHelloConsumer.goServerHello(ClientHello.java:1252)
                at java.base/sun.security.ssl.ClientHello$T13ClientHelloConsumer.consume(ClientHello.java:1188)
                at java.base/sun.security.ssl.ClientHello$ClientHelloConsumer.onClientHello(ClientHello.java:851)
                at java.base/sun.security.ssl.ClientHello$ClientHelloConsumer.consume(ClientHello.java:812)
                at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
                at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
                at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1267)
                at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1254)
                at java.base/java.security.AccessController.doPrivileged(AccessController.java:691)
                at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1199)
                at org.apache.tomcat.util.net.SecureNioChannel.tasks(SecureNioChannel.java:443)
                at org.apache.tomcat.util.net.SecureNioChannel.handshakeUnwrap(SecureNioChannel.java:507)
                at org.apache.tomcat.util.net.SecureNioChannel.handshake(SecureNioChannel.java:238)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1568)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.base/java.lang.Thread.run(Thread.java:832)

```
I believe this fix made it into bc 1.69 which is currently beta - any chance of a swift release? Thanks

**Comment by dghgit** [comment] 2021-02-12 23:55
The latest beta is at https://www.bouncycastle.org/betas

This was fixed in 1.68 though, would you provide a list of what is in META-INF for the jar you are using? Please move comments to #881

**Comment by jbakermk** [comment] 2021-02-13 09:02
> This was fixed in 1.68 though, would you provide a list of what is in META-INF for the jar you are using? 

Which jar? There are loads in the WEB-INF/lib directory, all related to the project. But within the bc jar, a huge list under META-INF/versions. This seems to match the bc 1.68 jars downloaded from mvnrepository.

Can you be more specific so we can help further?

**Comment by jbakermk** [comment] 2021-02-13 09:46
I've looked further into this issue. Our project was creating a 'fat jar' of dependencies and that causes the issue with v1.68. If the bc jars are removed from the fat jar and deployed separately, the error doesn't occur. I've got no idea why this would be an issue.

**Comment by dghgit** [comment] 2021-02-13 12:49
The "fat jar" concept doesn't work with the JCE/JCA - it's buried too deep in the JVM. As weird as it sounds, in some ways it does make sense - cryptography providers affect the security of the JVM, you would want extra caution around how they are handled otherwise the providing assurances, such as those around FIPS, become impossible.

**Comment by dghgit** [comment] 2021-02-13 13:17
The other thing I should add is you should probably look at the BC JSEE - this is not a criticism of the JSSE provider shipped with the JVM, but Oracle announced as of Java 1.9 that they were unable to keep supporting the FIPS mode, if FEDRamp is in your future, the BCJSSE is your best choice.

**Comment by alvdavi** [comment] 2021-02-16 22:34
> I've looked further into this issue. Our project was creating a 'fat jar' of dependencies and that causes the issue with v1.68. If the bc jars are removed from the fat jar and deployed separately, the error doesn't occur. I've got no idea why this would be an issue.

The solution to make this work in BouncyCastle makes use of the multi-release jar feature:
https://openjdk.java.net/jeps/238

This means the jar includes two (or more) copies of the class files, for different versions of java. If your fat jar creation logic is not multi-release jar aware, it will only include one copy of the class files, the default one. For compatibility reasons, the default ones are the ones targeting JDK8 and older (as those versions are not aware of what a multi-release jar is)

**Comment by ErikBergfurInfor** [comment] 2021-12-14 19:51
How would you get access to the betas?

**Comment by jeffhuang26** [comment] 2022-08-15 16:55
I hit same issue on bc-fips-1.0.2.jar. Which fips version will this fix get into? @dghgit

**Comment by dghgit** [comment] 2022-08-15 17:14
It's in 2.0.0.

**Comment by dghgit** [comment] 2022-08-15 23:46
> How would you get access to the betas?

Some how I missed this, the betas are made available to support contract holders only - aside from the costs involved, they can't be made available for general access till we get sign off from NIST.

**Comment by mouse07410** [comment] 2022-08-15 23:48
Not my business, but it's there any reason to concentrate on any other JDK versions besides 11 and 17 (LTS releases)?

**Comment by sawanverma** [comment] 2023-09-12 08:59
@dghgit I am using Java 110.20 from Amzn Corretto and org.bouncycastle:bc-fips:1.0.2.3. I have hit the same issue as above "Could not generate XDH keypair".

I tried  System.setProperty("jdk.tls.namedGroups", "secp256r1, secp384r1, ffdhe2048, ffdhe3072"); but it doesnt work.
I cant move the security postion of bc-fips. It has to be at the top for fedramp. Please suggest when can we expect 2.0.0 bc-fips to be out. or any workaround.

**Comment by dghgit** [comment] 2023-09-12 10:55
Don't the use SunJSSE. To start with it's not FIPS compliant.

**Comment by sawanverma** [comment] 2023-09-13 05:07
> Don't the use SunJSSE. To start with it's not FIPS compliant.

Hi, not sure what do you mean by this. I am using bc-fips-1.0.2.3 which is FIPS complaint. and marking bouncy castle as top most security provider

**Comment by dghgit** [comment] 2023-09-13 06:04
See SP 800-52.

**Comment by sawanverma** [comment] 2023-09-13 09:05
Ok got that and hence for the same reason we are using bc-fips security provider. Am I missing something? Please elaborate.

**Comment by dghgit** [comment] 2023-09-13 09:08
Are you using the BCJSSE in FIPS mode?

**Comment by sawanverma** [comment] 2023-09-15 07:11
> Are you using the BCJSSE in FIPS mode?

Not really or may be I am not sure. I am doing the following

lazy val bouncyCastle = "org.bouncycastle" % "bc-fips" % "1.0.2.3"
import org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider

Security.insertProviderAt(new BouncyCastleFipsProvider(), 1)

And I have my other service running on SSL , it throws the mentioned error while connecting to them.

**Comment by dghgit** [comment] 2023-09-15 07:18
You need to be using the BCJSSE. The Java JSSE does an internal cast to a class that does not exist as far as the FIPS module is concerned.

**Comment by sawanverma** [comment] 2023-09-15 07:53
It will be very helpful if you can provide how to use that with above code snippet?

**Comment by zchen-panzura** [comment] 2024-12-09 05:29
> Are you using the BCJSSE in FIPS mode?

how can we do it?

I have the following in the code:
Security.insertProviderAt(new BouncyCastleFipsProvider(), 1);

but got the error:
Caused by: java.security.InvalidAlgorithmParameterException: AlgorithmParameterSpec not recognized: java.security.spec.NamedParameterSpec
        at org.bouncycastle.jcajce.provider.ProvEdEC$KeyPairGeneratorSpi.initialize(ProvEdEC.java:477)
        at java.base/sun.security.ssl.XDHKeyExchange$XDHEPossession.<init>(XDHKeyExchange.java:104)

**Comment by dghgit** [comment] 2024-12-09 05:32
You need to be using the BCJSSE (the bctls-fips jar).

**Comment by zchen-panzura** [comment] 2024-12-09 05:41
> You need to be using the BCJSSE (the bctls-fips jar).

I have in build.gradle:
implementation 'org.bouncycastle:bctls-fips:1.0.19'

**Comment by dghgit** [comment] 2024-12-09 05:45
I'm not sure how that's relevant - if you look at the stack trace bctls is clearly not in use. bctls needs to be installed like a regular provider, with the appropriate priority.

**Comment by zchen-panzura** [comment] 2024-12-09 06:24
> I'm not sure how that's relevant - if you look at the stack trace bctls is clearly not in use. bctls needs to be installed like a regular provider, with the appropriate priority.

Looks like the exception is not happening anymore:
Caused by: java.security.InvalidAlgorithmParameterException: AlgorithmParameterSpec not recognized: java.security.spec.NamedParameterSpec
at org.bouncycastle.jcajce.provider.ProvEdEC$KeyPairGeneratorSpi.initialize(ProvEdEC.java:477)
at java.base/sun.security.ssl.XDHKeyExchange$XDHEPossession.(XDHKeyExchange.java:104)

after adding:
      Security.insertProviderAt(new BouncyCastleJsseProvider(), 2);
