### ISSUE TITLE
Issue while using RSA private (PKCS#1) keys 

### ISSUE THREAD

**Issue by Manojkumar-kulkarni** [bcgit/bc-java#860] opened 2020-12-29 11:07 UTC
We are using bouncy-castle crypto JAVA APIs for creating SSL context for secure GRPC communication. 
While using RSA private keys(PKCS#1) created using step-ca, getting PEER_DID_NOT_RETURN_A_CERTIFICATE error, which is not the case with the OpenSSL RSA private keys(PKCS#1). When we convert the step-ca PKCS#1 key to PKCS#8 key error is not observed. Any help on this is really appreciable.

Following is the code snippet we were trying:
	if (trust == null) {
      _channel = ManagedChannelBuilder.forAddress(host, port).usePlaintext()
          .intercept(new HeaderClientInterceptor(null)).build();
    } else {
      SslContext sslctx;
      try {
        sslctx = GrpcSslContexts.forClient().keyManager(clientCert, key, passphrase).trustManager(trust).build();
      } catch (IllegalArgumentException iae) {
        logger.trace("Exception in creating SSL context for channel using pem encoded certificates");
        if (Security.getProvider("BC") == null) {
          Security.addProvider(new BouncyCastleProvider());
        }

        try {
          final PrivateKey privkey = getPrivateKey(key, passphrase);
          final X509Certificate x509chain = this.getX509Certificate(clientCert);

          sslctx = GrpcSslContexts.forClient().keyManager(privkey, x509chain).trustManager(trust).build();
        } catch (CertificateException ce) {
          logger.error("CertificateException in creating SSL context: " + ce.getMessage());
          throw new SSLException(ce);
        }
      }
	}	
	
	private final X509Certificate getX509Certificate(final File clientCert) throws IOException, CertificateException {
    final PEMParser certparser = new PEMParser(new FileReader(clientCert));
    final Object obj;
    try {
      obj = certparser.readObject();
    } finally {
      certparser.close();
    }

    final X509CertificateHolder holder;
    if (obj instanceof X509CertificateHolder) {
      holder = (X509CertificateHolder)obj;
    } else {
      final IOException err = new IOException("Unable to read trust chain certificate file");
      logger.error(err.getMessage(), err);
      throw err;
    }

    return new JcaX509CertificateConverter().setProvider( "BC" ).getCertificate(holder);
  }

  private final PrivateKey getPrivateKey(final File key, final String passphrase) throws IOException, CertificateException {
    final PEMParser parser = new PEMParser(new FileReader(key));
    final Object obj;
    try {
      obj = parser.readObject();
    } finally {
      parser.close();
    }

    final PEMKeyPair pemkp;
    if (obj instanceof PEMKeyPair) {
      pemkp = (PEMKeyPair) obj;
    } else if (obj instanceof PEMEncryptedKeyPair) {
      final PEMEncryptedKeyPair encpair = (PEMEncryptedKeyPair) obj;
      final PEMDecryptorProvider provider = new BcPEMDecryptorProvider(passphrase.toCharArray());
      pemkp = encpair.decryptKeyPair(provider);
    } else {
      final IOException err = new IOException("Unable to read key file");
      logger.error(err.getMessage(), err);
      throw err;
    }

    return new JcaPEMKeyConverter().setProvider("BC").getKeyPair(pemkp).getPrivate();
  }

**Comment by Manojkumar-kulkarni** [comment] 2021-02-04 13:32
did anyone face a similar issue?

**Comment by dghgit** [comment] 2021-05-31 01:46
I'd really need to see a step-ca PKCS#1 key.

**Comment by Manojkumar-kulkarni** [comment] 2021-06-02 10:25
@dghgit please find the attached key.

[pkcs#1.zip](https://github.com/bcgit/bc-java/files/6583732/pkcs.1.zip)

**Comment by dghgit** [comment] 2021-06-03 08:10
The key's not valid. The modulus is a negative number, there should be a 00 byte at the start of it. ASN.1 integers are always signed.

**Comment by dghgit** [comment] 2021-06-13 13:03
Closed as not a bug (well at least not one of ours...)

**Closed by dghgit** 2021-06-13 13:03 UTC
