### ISSUE TITLE
bcprov-ext-jdk18on-1.78 missing OSGi manifest

### ISSUE THREAD

**Issue by domagojcc** [bcgit/bc-java#1630] opened 2024-04-18 11:34 UTC
The library has a plain Java manifest. It is missing OSGi entries, and it is thus not usable in any OSGi environment.

**Comment by cipherboy** [comment] 2024-04-18 12:18
@domagojcc This should be resolved in 1.78.1; there are betas available on the website for it. I think this is a duplicate of #1621. :-)

**Comment by dghgit** [comment] 2024-04-18 23:15
Use bcprov-jdk18on-1.78.1 the -ext- versions have been the same as the non "-ext-" versions for a while now, we're no longer releasing them.

**Comment by dghgit** [comment] 2024-04-21 02:32
We will get a redirect installed on Maven Central for this one. Having to get some help as the tool we usually use for deploy Maven updates appears unable to do it.

**Comment by nmck257** [comment] 2024-04-29 17:20
> Use bcprov-jdk18on-1.78.1 the -ext- versions have been the same as the non "-ext-" versions for a while now, we're no longer releasing them.

Can you easily clarify at which version these artifacts became equivalent?

**Comment by dghgit** [comment] 2024-04-30 06:12
bcprov- without the ext. The ext originally signified we'd been advised that some of the algorithms in the jar had patents on them, somewhere, at this point all the ones we've been made aware of have expired.

**Comment by dghgit** [comment] 2024-07-15 15:33
Yes, this is correct. Thanks for the confirmation - I'll close.

**Closed by dghgit** 2024-07-15 15:33 UTC
