### ISSUE TITLE
Code-cleanup of bcpg results in NoSuchAlgorithmException: SHA56 MessageDigest not available

### ISSUE THREAD

**Issue by groissi** [bcgit/bc-java#1866] opened 2024-10-14 16:56 UTC
The code-cleanup of the class `pg/src/main/java/org/bouncycastle/openpgp/operator/jcajce/OperatorHelper.java` in commit [da84c86aba213aa68801fbede1ff71047f80ca4a](https://github.com/bcgit/bc-lts-java/commit/da84c86aba213aa68801fbede1ff71047f80ca4a) introduced an error when using the `PGPDigestCalculator` with `SHA256` (`NoSuchAlgorithmException: SHA56 MessageDigest not available`).

The overall stack-trace is:
> Caused by: java.security.NoSuchAlgorithmException: SHA56 MessageDigest not available
> 	at sun.security.jca.GetInstance.getInstance(GetInstance.java:159) ~[?:1.8.0_412]
> 	at java.security.Security.getImpl(Security.java:695) ~[?:1.8.0_412]
> 	at java.security.MessageDigest.getInstance(MessageDigest.java:170) ~[?:1.8.0_412]
> 	at org.bouncycastle.jcajce.util.DefaultJcaJceHelper.createMessageDigest(Unknown Source) ~[bcprov-lts8on-2.73.6.jar:?]
> 	at org.bouncycastle.openpgp.operator.jcajce.OperatorHelper.createDigest(Unknown Source) ~[bcpg-lts8on-2.73.6.jar:?]
> 	at org.bouncycastle.openpgp.operator.jcajce.JcaPGPDigestCalculatorProviderBuilder$1.get(Unknown Source) ~[bcpg-lts8on-2.73.6.jar:?]
> 	... 10 more

The usage resulting in that behavior is:
> PGPDigestCalculatorProvider pgpDigestCalculatorProvider = new JcaPGPDigestCalculatorProviderBuilder().build();
> PGPDigestCalculator sha256Calc = pgpDigestCalculatorProvider.get(HashAlgorithmTags.SHA256);

**Comment by dghgit** [comment] 2024-10-15 01:27
This doesn't make any sense. It's even regression tested. What providers are in use here?

**Comment by groissi** [comment] 2024-10-15 08:39
As you can see in the stack-trace, it's `bcprov-lts8on-2.73.6` and `bcpg-lts8on-2.73.6`. I switched back to the versions 2.73.5 and everything worked like a charm again.

**Comment by groissi** [comment] 2024-10-15 08:42
The method `String getDigestName(int hashAlgorithm)` was removed from `OperatorHelper` and now the `PGPUtil.getDigestName(int algorithm)` is used instead.

**Comment by vanitasvitae** [comment] 2024-10-15 14:16
> Caused by: java.security.NoSuchAlgorithmException: SHA56 MessageDigest not available

Perhaps you made a typo? (SHA*56* instead of SHA*256*)

**Comment by vanitasvitae** [comment] 2024-10-15 14:22
> Caused by: java.security.NoSuchAlgorithmException: SHA**56** MessageDigest not available

Looks like the `2` was cut off by accident.
Apparently this was a bug that was fixed with https://github.com/bcgit/bc-java/commit/ed9b3bc1babee4615705968a1162729a8764b7bb

**Comment by groissi** [comment] 2024-10-15 15:40
Thx, I thought it had something to do with that part of the code, but unfortunately had no time for detailed analysis.

BTW: Is it possible that there are no debug-builds available anymore?! Otherwise, where can I find them?

**Comment by dghgit** [comment] 2024-10-15 19:16
Ah, actually, looking at it, the PG build for LTS was built on the 8th, so the bug made it in there. We should be releasing an update in the next few weeks.

**Comment by dghgit** [comment] 2024-11-03 04:35
Fixed in 1.79.

**Closed by dghgit** 2024-11-03 04:35 UTC
